# Somatic frameshift and stop-gain by tissue of origin

In [ ]:
# 1) import modules
import os
import re
import json
import pandas as pd
import scipy
import time
import requests
import hashlib
import csv
import random
from collections import defaultdict
import numpy as np    
import statsmodels.api as sm   
import seaborn as sns
from scipy.signal import find_peaks
import matplotlib.pyplot as plt

## Comparing between groups (tissue types and germline included)

In [465]:
start_time_block2=time.asctime(time.localtime())
print(start_time_block2)

somaticconcat_allTSG=pd.DataFrame()
alloutputdf=pd.DataFrame()

#3-all TSG, excluding splice region, all output stats to this df gene-wise
allTSG_df_nospliceregion=pd.DataFrame()

FLAG1_count=FLAG5_count=FLAGFISHER_count=0

cosmicconcat_OT_parent_annotated_readcsv=pd.read_csv("/Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/COSMIC/Cosmic_MutantCensus_Tsv_v98_GRCh38/cosmicconcat_41TSGs_NCITtoOT_dropna_parentOT_11-25-24.txt", sep="\t")
        
parentpath="/Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023"
os.chdir(parentpath)
# loading VEP consequence titles (category names) to use as index to join cbio and clinvar processed dfs:
VEP_calc_consequences=pd.read_csv("VEP_calculated_consequences_8-26-24.txt", sep="\t", header=None) #edited to add 'splice_site_variant' on 8-26-24


#read file with folder names and MANE Select transcript identifiers (or MANE Plus Clinical in the case of SMARCA4)
TranscriptID= pd.read_csv("TSGfolder_MANESelect_names_aalength_GeneIDs_6-13-24.txt", sep="\t")

Hypermutators=pd.read_csv("cbio_sampleinfo_tmb_gt10_12-14-23.txt", sep="\t")

for index, row in TranscriptID.iterrows():
    
    # Loop through each folder name
    folder_name=TranscriptID.loc[index]["Gene Symbol"]
    #if folder name exists, list all files in that folder then change directory to that folder
    if os.path.exists(folder_name) and os.path.isdir(folder_name):# and (folder_name == "RB1"):
        filelist=os.listdir(folder_name)
        os.chdir(folder_name)
        
        
        clinvar_cbio_tocompare=pd.read_csv("Python_coderun_6-13-24_clinvar_extract_and_process_again/Python_clinvar_cbio_tocompare_8-16-24.txt", sep="\t")
        Variation_interpretation_toexclude = ["Pathogenic", "Likely pathogenic", "Pathogenic/Likely pathogenic", "Conflicting interpretations of pathogenicity greater than or equal to 75"]
        clinvar_cbio_tocompare_VUSLBB=clinvar_cbio_tocompare[~clinvar_cbio_tocompare["GL_first_Description"].isin(Variation_interpretation_toexclude)]
        #print("shared count")
        #print(len(clinvar_cbio_tocompare))
        #print("shared that are VUSLBB")
        #print(len(clinvar_cbio_tocompare_VUSLBB))
        cbio_VEP=pd.read_csv("Python_coderun_7-11-24_cbio_process_again/Python_cbio_processed_VEP_MANE_CAID_OTtissue_10-24-24.txt", sep="\t")
        #print("cbio VEP len")
        cbioCount1=len(cbio_VEP)
        #print(len(cbio_VEP))
        VEP_categories_tofilter_list=["synonymous_variant","5_prime_UTR_variant", "3_prime_UTR_variant", "non_coding_transcript_exon_variant", "intron_variant", "non_coding_transcript_variant", "upstream_gene_variant", "downstream_gene_variant", "regulatory_region_ablation", "regulatory_region_amplification", "regulatory_region_variant", "intergenic_variant", "splice_region_variant"] #8-23-24 #, ">=50bp_indel"]
        cbio_VEP=cbio_VEP[~cbio_VEP["collapsed_Consequence"].isin(VEP_categories_tofilter_list)]
        #print("cbio VEP len after filter VEP categories")
        #print(len(cbio_VEP))
        cbioCount2=len(cbio_VEP)
        Hypermutators_to_filter=Hypermutators.set_index('uniqueSampleKey').index
        #print("with hypermutators count QC same as above")
        totalbeforehypermutatorfilter=len(cbio_VEP)
        #print(len(cbio_VEP))
        cbio_VEP_nohypermutator=cbio_VEP[~cbio_VEP["uniqueSampleKey"].isin(Hypermutators_to_filter)]
        cbio_VEP=cbio_VEP_nohypermutator
        #print("without hypermutators count")
        #print(len(cbio_VEP))
        #print("% vars lost to hypermutator filter=#total-#afterfilter/#total")
        #print(((totalbeforehypermutatorfilter-len(cbio_VEP))*100)/totalbeforehypermutatorfilter)
        removetheseVUSLBB=clinvar_cbio_tocompare_VUSLBB["@id"]
        cbio_VEP_noVUSLBB=cbio_VEP[~cbio_VEP["@id"].isin(removetheseVUSLBB)]
        #print("without VUSLBB")
        #print(len(cbio_VEP_noVUSLBB))
        #print("# variants lost after VUSLBB filter")
        #print(len(cbio_VEP)-len(cbio_VEP_noVUSLBB))
        #print("% vars lost to VUSLBB filter=#total-#afterfilter/#total")
        #print(((len(cbio_VEP)-len(cbio_VEP_noVUSLBB))*100)/len(cbio_VEP))
        cbio_VEP_cancertypeall=cbio_VEP_noVUSLBB
        print(len(cbio_VEP_cancertypeall))
        #cbio=pd.concat([cbio, cbio_VEP_cancertype])
        cbio_VEP_cancertype_uniqueOT=cbio_VEP_cancertypeall[cbio_VEP_cancertypeall["unique_count_parents_in_OncoTree"]==1]
        print(len(cbio_VEP_cancertype_uniqueOT))
        
        cbio_VEP_cancertype_uniqueOT_0tummorAltCount=cbio_VEP_cancertype_uniqueOT[cbio_VEP_cancertype_uniqueOT["tumorAltCount"]==0]
        cbio_VEP_cancertype_uniqueOT_no0tummorAltCount=cbio_VEP_cancertype_uniqueOT.drop(cbio_VEP_cancertype_uniqueOT_0tummorAltCount.index)
        print(len(cbio_VEP_cancertype_uniqueOT_no0tummorAltCount))
        
        folder_name_aslist=[folder_name]
        cosmicconcat_OT_parent_annotated_readcsv_renamecolumns=cosmicconcat_OT_parent_annotated_readcsv.rename(columns={"unique_count_parents_in_OncoTree":'empty1', 'parent_tissue_code_list': 'empty2', "count_parents_in_OncoTree":"empty3", "parent_tissue_code":"empty4", '1': "unique_count_parents_in_OncoTree", '2': "parent_tissue_code_list", '3': "count_parents_in_OncoTree", '4':"parent_tissue_code"})

        cosmic=cosmicconcat_OT_parent_annotated_readcsv_renamecolumns[cosmicconcat_OT_parent_annotated_readcsv_renamecolumns["GENE_SYMBOL"].isin(folder_name_aslist)==True]
        print(len(cosmic))
        cosmic_uniqueOT=cosmic[cosmic["unique_count_parents_in_OncoTree"]==1]
        
        somaticconcat=pd.concat([cbio_VEP_cancertype_uniqueOT_no0tummorAltCount,cosmic_uniqueOT])
        print(len(somaticconcat))
        
        
        somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")
        somaticconcat=somaticconcat.rename(columns={"level_0":"level_0_hgvsg"})
        somaticconcat=somaticconcat.reset_index()
        
        somaticconcat_allTSG=pd.concat([somaticconcat_allTSG,somaticconcat])
        print(len(somaticconcat_allTSG))
        
        dfparentOT=pd.DataFrame(somaticconcat["parent_tissue_code"].value_counts())
        dfparentOT_filtergte25=dfparentOT[dfparentOT["count"]>=25]
        dfparentOT_filtergte25_resetindex=dfparentOT_filtergte25.reset_index()
        display(dfparentOT)
        adjpfactor=len(dfparentOT_filtergte25_resetindex)
        if (adjpfactor!=0):
            df_forstats=VEP_calc_consequences.set_index(0)
            
            for index, row in dfparentOT_filtergte25_resetindex.iterrows():
                OTparent=dfparentOT_filtergte25_resetindex.loc[index]["parent_tissue_code"]
                somaticconcat_singleOTparent=somaticconcat[somaticconcat["parent_tissue_code"].str.contains(OTparent.split("(")[0])==True]
                #print(len(somaticconcat_singleOTparent), OTparent)
                
                #initialize default dict to select 1 variant at random from list of variants per patient (for patients with multiple variants in the same gene):
                cbio_VEP_dict=defaultdict(list)
            
            
                # loading VEP consequence titles (categories) to use as index to join randomavg dfs:
                cbio_VEP_calc_consequences=VEP_calc_consequences
                cbio_VEP_randomavg_means=cbio_VEP_calc_consequences.set_index(0)
                #making dictionary of list of variants per patient id in the form ({patient1: [var1consequence, var2consequence, var3consequence,...], patient2:[var1consequence,var2consequence,..]})
                cbio_VEP_cancertype=somaticconcat_singleOTparent
                for index, row in cbio_VEP_cancertype.iterrows():
                    patientid=cbio_VEP_cancertype.loc[index]["patientid"]
                    VEPresult=cbio_VEP_cancertype.loc[index]["collapsed_Consequence"]
                    cbio_VEP_dict[patientid].append(VEPresult)

                #print(len(cbio_VEP_dict))
                #randomly selecting 1 variant per patient id and summarizing distribution, repeating 5 times
                for i in range(5):
                    cbio_VEP_random = {k:random.choice(v) for k,v in list(cbio_VEP_dict.items())}
                    list_VEP_random=[]
                    for key, val in cbio_VEP_random.items():
                        eachrow=[key,val]
                        list_VEP_random.append(eachrow)
                    #convert list to df of 1 variant per patient [patient1:var2consequence, patient2:var1consequence, ...]
                    dfconvert= pd.DataFrame(list_VEP_random)
                    #summarize counts per VEP category and convert to df having VEP category as index
                    cbio_VEP_randomavg=pd.DataFrame(dfconvert[1].value_counts())
                    #above is a df of current random selection having row header=VEP category and only 1 column of the counts per category (aka row) derived from current random selection
                    #rename counts column in above df with the loop number (1/2/3/4/5) + join together with previous df (if not the 1st random selection of 5) and calc mean of all 5 sets of distributions
                    rename=f"VEP_count_{i}"
                    cbio_VEP_randomavg_rename=cbio_VEP_randomavg.rename(columns={"count":rename})
                    cbio_VEP_randomavg_means=cbio_VEP_randomavg_means.join(cbio_VEP_randomavg_rename)
                #replace all missing values with 0 to calc mean
                cbio_VEP_randomavg_means_fill0=cbio_VEP_randomavg_means.fillna(0)
                #calc mean
                cbio_VEP_randomavg_means_fill0['mean']=cbio_VEP_randomavg_means_fill0.mean(axis=1)


                ## added 3-12-25:
                #dfparentOT_filtergte25_resetindex.groupby(by=["parent_tissue_code","collapsed_Consequence"]).size()

            
                #rename somatic column in cbio df
                cbio_VEP_randomavg_means_fill0_rename=cbio_VEP_randomavg_means_fill0.rename(columns={"mean":f"{OTparent}"})
                
                cbio_VEP_randomavg_means_fill0_rename=cbio_VEP_randomavg_means_fill0_rename.filter(items=[f"{OTparent}"])
                
                
                #combine gl and s dfs
                df_forstats = df_forstats.join(cbio_VEP_randomavg_means_fill0_rename)
                
            clinvar_VEP_cancertype=pd.read_csv("Python_coderun_6-13-24_clinvar_extract_and_process_again/Python_clinvar_processed_VEP_MANE_8-15-24.txt", sep="\t")
         
            clinvar_VEP_MANE=VEP_calc_consequences.set_index(0)
            #create list with each VEP category in data, plus occurrence list of number of times each variant seen in that category
            clinvar_VEPresult=defaultdict(list)
            for index, row in clinvar_VEP_cancertype.iterrows():
                VEPresult=clinvar_VEP_cancertype.loc[index]["collapsed_Consequence"]
                variantcount=clinvar_VEP_cancertype.loc[index]["Occurrence"]
                clinvar_VEPresult[VEPresult].append(variantcount)
            #sum the list of occurrence per VEP category
            clinvar_VEPresult_sumoccurrence = {k: sum(v) for (k, v) in clinvar_VEPresult.items()}
            #create dataframe from dictionary
            clinvar_dfconvert=pd.DataFrame.from_dict(clinvar_VEPresult_sumoccurrence, orient='index')
            #join with VEP consequence df
            clinvar_VEP=clinvar_VEP_MANE.join(clinvar_dfconvert)
            #replace missing values with 0
            clinvar_VEP_fill0=clinvar_VEP.fillna(0)
            #rename germline column
            clinvar_VEP_fill0_rename=clinvar_VEP_fill0.rename(columns={0:"VEP_germline"})
                
            df_gl_s = df_forstats.join(clinvar_VEP_fill0_rename)
                
            #filter out categories filtered by cbio (excep for TERT- diff set since cbio includes promoter variants)
            if folder_name=="TERT":
                VEP_categories_tofilter_list=["synonymous_variant", "3_prime_UTR_variant", "intron_variant", "downstream_gene_variant"]
            else:    
                VEP_categories_tofilter_list=["synonymous_variant","5_prime_UTR_variant", "3_prime_UTR_variant", "non_coding_transcript_exon_variant", "intron_variant", "non_coding_transcript_variant", "upstream_gene_variant", "downstream_gene_variant", "regulatory_region_ablation", "regulatory_region_amplification", "regulatory_region_variant", "intergenic_variant", "splice_region_variant", "splice_donor_variant","splice_acceptor_variant", "missense_variant", "inframe_deletion", ">=50bp_indel", "inframe_insertion", "protein_altering_variant", "start_lost", "stop_lost"]

            df_gl_s_filter=df_gl_s.drop(VEP_categories_tofilter_list)
            #display(df_gl_s_filter)
            #df_gl_s_allgte5=df_gl_s_filter[(df_gl_s_filter.ne(0)).any(axis=1)]
            df_gl_s_allgte5=df_gl_s_filter[~(df_gl_s_filter < 5).all(axis=1)]
            display(df_gl_s_allgte5)
            print(df_gl_s_allgte5.sum())
             #run chi-square test from scipy
            from scipy.stats import chi2_contingency
            c_nospliceregion, p_nospliceregion, dof_nospliceregion, expected_nospliceregion = chi2_contingency(df_gl_s_allgte5)
            print(c_nospliceregion, p_nospliceregion, dof_nospliceregion) 
            display(df_gl_s_allgte5)
            print(expected_nospliceregion)

            expected_df=pd.DataFrame(expected_nospliceregion)
            count_less_than_5 = (expected_df < 5).sum().sum()
            if count_less_than_5/expected_df.size > 0.25:
                FLAG5=1
            else:
                FLAG5=0

            import numpy as np    
            import statsmodels.api as sm   
            table_nospliceregion = sm.stats.Table(df_gl_s_allgte5)   # Standardized residuals

               
            #Pearson_residuals to output
            Pearson_residuals_standardized_nospliceregion = table_nospliceregion.standardized_resids
            display(Pearson_residuals_standardized_nospliceregion)
            print(f"FLAG5 = {FLAG5}")

            outputdf=Pearson_residuals_standardized_nospliceregion
            alloutputdf=pd.concat([alloutputdf,outputdf])

        print("Current directory:", os.getcwd())
        os.chdir(parentpath)
    else:
        print(f"Folder '{folder_name}' not found.")

end_time_block2=time.asctime(time.localtime())
print(end_time_block2)

Wed Mar 12 16:48:28 2025
131
125
125
471
596
596

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:16: DtypeWarning: Columns (24,177) have mixed types. Specify dtype option on import or set low_memory=False.
  cosmicconcat_OT_parent_annotated_readcsv=pd.read_csv("/Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/COSMIC/Cosmic_MutantCensus_Tsv_v98_GRCh38/cosmicconcat_41TSGs_NCITtoOT_dropna_parentOT_11-25-24.txt", sep="\t")
/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
Myeloid (MYELOID)                  523
Lymphoid (LYMPH)                    14
Lung (LUNG)                         13
Esophagus/Stomach (STOMACH)          9
Kidney (KIDNEY)                      7
Bowel (BOWEL)                        6
Skin (SKIN)                          6
Pancreas (PANCREAS)                  4
CNS/Brain (BRAIN)                    3
Breast (BREAST)                      3
Liver (LIVER)                        3
Bladder/Urinary Tract (BLADDER)      2
Bone (BONE)                          2
Head and Neck (HEAD_NECK)            1

                    Myeloid (MYELOID)  VEP_germline
0
stop_gained                      79.4          32.0
frameshift_variant              347.4          30.0

Myeloid (MYELOID)    426.8
VEP_germline          62.0
dtype: float64
31.672643519768272 1.8247455079090336e-08 1

                    Myeloid (MYELOID)  VEP_germline
0
stop_gained                      79.4          32.0
frameshift_variant              347.4          30.0

[[ 97.26988543  14.13011457]
 [329.53011457  47.86988543]]

                    Myeloid (MYELOID)  VEP_germline
0
stop_gained                 -5.789845      5.789845
frameshift_variant           5.789845     -5.789845

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/WT1
634
634
634
2258
2877
3473

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
Kidney (KIDNEY)                   2741
CNS/Brain (BRAIN)                   63
Adrenal Gland (ADRENAL_GLAND)       16
Pancreas (PANCREAS)                 13
Lung (LUNG)                          8
Uterus (UTERUS)                      7
Bowel (BOWEL)                        6
Thyroid (THYROID)                    5
Skin (SKIN)                          4
Esophagus/Stomach (STOMACH)          4
Bladder/Urinary Tract (BLADDER)      2
Breast (BREAST)                      2
Pleura (PLEURA)                      1
Bone (BONE)                          1
Ovary/Fallopian Tube (OVARY)         1
Liver (LIVER)                        1
Head and Neck (HEAD_NECK)            1
Prostate (PROSTATE)                  1

                    Kidney (KIDNEY)  CNS/Brain (BRAIN)  VEP_germline
0
stop_gained                   362.8                9.0          84.0
frameshift_variant           1422.2               24.8         135.0

Kidney (KIDNEY)      1785.0
CNS/Brain (BRAIN)      33.8
VEP_germline          219.0
dtype: float64
36.88315752224788 9.793188331814717e-09 2

                    Kidney (KIDNEY)  CNS/Brain (BRAIN)  VEP_germline
0
stop_gained                   362.8                9.0          84.0
frameshift_variant           1422.2               24.8         135.0

[[ 399.25556973    7.56013348   48.98429679]
 [1385.74443027   26.23986652  170.01570321]]

                    Kidney (KIDNEY)  CNS/Brain (BRAIN)  VEP_germline
0
stop_gained               -5.879064           0.599331      6.010357
frameshift_variant         5.879064          -0.599331     -6.010357

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/VHL
268
244
244
169
413
3886

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
Liver (LIVER)                      117
Kidney (KIDNEY)                     88
Lung (LUNG)                         63
Bowel (BOWEL)                       36
Esophagus/Stomach (STOMACH)         22
Pancreas (PANCREAS)                 12
Soft Tissue (SOFT_TISSUE)           10
Bladder/Urinary Tract (BLADDER)      9
Breast (BREAST)                      7
Biliary Tract (BILIARY_TRACT)        6
Uterus (UTERUS)                      6
CNS/Brain (BRAIN)                    6
Skin (SKIN)                          6
Head and Neck (HEAD_NECK)            5
Ovary/Fallopian Tube (OVARY)         4
Thyroid (THYROID)                    4
Bone (BONE)                          3
Lymphoid (LYMPH)                     3
Other (OTHER)                        3
Prostate (PROSTATE)                  2
Thymus (THYMUS)                      1

,Liver (LIVER),Kidney (KIDNEY),Lung (LUNG),Bowel (BOWEL),VEP_germline
0,,,,,
stop_gained,38.0,25.0,19.6,12.0,503.0
frameshift_variant,38.0,30.6,21.0,12.0,671.0

Liver (LIVER)        76.0
Kidney (KIDNEY)      55.6
Lung (LUNG)          40.6
Bowel (BOWEL)        24.0
VEP_germline       1174.0
dtype: float64
2.3406190464024337 0.6733838681248366 4

,Liver (LIVER),Kidney (KIDNEY),Lung (LUNG),Bowel (BOWEL),VEP_germline
0,,,,,
stop_gained,38.0,25.0,19.6,12.0,503.0
frameshift_variant,38.0,30.6,21.0,12.0,671.0

[[ 33.14669391  24.24942344  17.7073128   10.46737703 512.02919282]
 [ 42.85330609  31.35057656  22.8926872   13.53262297 661.97080718]]

,Liver (LIVER),Kidney (KIDNEY),Lung (LUNG),Bowel (BOWEL),VEP_germline
0,,,,,
stop_gained,1.15511,0.207231,0.608063,0.636456,-1.404296
frameshift_variant,-1.15511,-0.207231,-0.608063,-0.636456,1.404296

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/TSC2

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

281
243
242
107
348
4234

                                 count
parent_tissue_code
Bladder/Urinary Tract (BLADDER)    110
Kidney (KIDNEY)                     56
Liver (LIVER)                       44
Lung (LUNG)                         24
Bowel (BOWEL)                       24
Esophagus/Stomach (STOMACH)         13
CNS/Brain (BRAIN)                   12
Head and Neck (HEAD_NECK)           12
Breast (BREAST)                     11
Skin (SKIN)                          9
Pancreas (PANCREAS)                  6
Biliary Tract (BILIARY_TRACT)        4
Lymphoid (LYMPH)                     3
Thyroid (THYROID)                    3
Bone (BONE)                          3
Soft Tissue (SOFT_TISSUE)            3
Ovary/Fallopian Tube (OVARY)         2
Uterus (UTERUS)                      2
Pleura (PLEURA)                      2
Adrenal Gland (ADRENAL_GLAND)        2
Prostate (PROSTATE)                  1
Other (OTHER)                        1
Cervix (CERVIX)                      1

,Bladder/Urinary Tract (BLADDER),Kidney (KIDNEY),Liver (LIVER),VEP_germline
0,,,,
stop_gained,49.8,16.2,20.0,344.0
frameshift_variant,36.2,28.8,16.0,470.0

Bladder/Urinary Tract (BLADDER)     86.0
Kidney (KIDNEY)                     45.0
Liver (LIVER)                       36.0
VEP_germline                       814.0
dtype: float64
10.86759639731508 0.012463806005545336 3

,Bladder/Urinary Tract (BLADDER),Kidney (KIDNEY),Liver (LIVER),VEP_germline
0,,,,
stop_gained,49.8,16.2,20.0,344.0
frameshift_variant,36.2,28.8,16.0,470.0

[[ 37.69622834  19.72477064  15.77981651 356.79918451]
 [ 48.30377166  25.27522936  20.22018349 457.20081549]]

,Bladder/Urinary Tract (BLADDER),Kidney (KIDNEY),Liver (LIVER),VEP_germline
0,,,,
stop_gained,2.753934,-1.084127,1.444301,-2.191318
frameshift_variant,-2.753934,1.084127,-1.444301,2.191318

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/TSC1

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:46: DtypeWarning: Columns (34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  cbio_VEP=pd.read_csv("Python_coderun_7-11-24_cbio_process_again/Python_cbio_processed_VEP_MANE_CAID_OTtissue_10-24-24.txt", sep="\t")
/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

17785
16662
16627
16599
33153
37387

                                     count
parent_tissue_code
Bowel (BOWEL)                         6133
Esophagus/Stomach (STOMACH)           5021
Lung (LUNG)                           4697
Breast (BREAST)                       2247
Head and Neck (HEAD_NECK)             1985
Liver (LIVER)                         1811
Ovary/Fallopian Tube (OVARY)          1615
Pancreas (PANCREAS)                   1252
Lymphoid (LYMPH)                      1245
CNS/Brain (BRAIN)                     1166
Bladder/Urinary Tract (BLADDER)        981
Skin (SKIN)                            865
Myeloid (MYELOID)                      704
Uterus (UTERUS)                        675
Biliary Tract (BILIARY_TRACT)          583
Prostate (PROSTATE)                    571
Thyroid (THYROID)                      325
Soft Tissue (SOFT_TISSUE)              311
Kidney (KIDNEY)                        270
Bone (BONE)                            138
Other (OTHER)                          136
Adrenal Gland (ADRENAL_GLAND)          106
Ampulla of Vater (AMPULLA_OF_VATER)    102
Cervix (CERVIX)                         71
Pleura (PLEURA)                         58
Thymus (THYMUS)                         43
Vulva/Vagina (VULVA)                    16
Peripheral Nervous System (PNS)         16
Penis (PENIS)                            3
Eye (EYE)                                3
Testis (TESTIS)                          3
Peritoneum (PERITONEUM)                  1

,Bowel (BOWEL),Esophagus/Stomach (STOMACH),Lung (LUNG),Breast (BREAST),Head and Neck (HEAD_NECK),Liver (LIVER),Ovary/Fallopian Tube (OVARY),Pancreas (PANCREAS),Lymphoid (LYMPH),CNS/Brain (BRAIN),...,Soft Tissue (SOFT_TISSUE),Kidney (KIDNEY),Bone (BONE),Other (OTHER),Adrenal Gland (ADRENAL_GLAND),Ampulla of Vater (AMPULLA_OF_VATER),Cervix (CERVIX),Pleura (PLEURA),Thymus (THYMUS),VEP_germline
0,,,,,,,,,,,,,,,,,,,,,
stop_gained,810.6,823.6,661.4,342.2,304.2,183.8,172.4,194.2,111.0,73.8,...,34.4,31.4,9.0,11.6,16.0,16.8,8.0,7.0,4.0,192.0
frameshift_variant,522.4,590.6,517.4,421.0,267.2,150.6,220.6,189.0,77.0,75.2,...,30.6,30.2,19.8,21.8,20.0,15.6,4.6,6.0,4.0,462.0

Bowel (BOWEL)                          1333.0
Esophagus/Stomach (STOMACH)            1414.2
Lung (LUNG)                            1178.8
Breast (BREAST)                         763.2
Head and Neck (HEAD_NECK)               571.4
Liver (LIVER)                           334.4
Ovary/Fallopian Tube (OVARY)            393.0
Pancreas (PANCREAS)                     383.2
Lymphoid (LYMPH)                        188.0
CNS/Brain (BRAIN)                       149.0
Bladder/Urinary Tract (BLADDER)         219.2
Skin (SKIN)                             228.0
Myeloid (MYELOID)                        98.6
Uterus (UTERUS)                         129.6
Biliary Tract (BILIARY_TRACT)           170.6
Prostate (PROSTATE)                     151.6
Thyroid (THYROID)                        70.0
Soft Tissue (SOFT_TISSUE)                65.0
Kidney (KIDNEY)                          61.6
Bone (BONE)                              28.8
Other (OTHER)                            33.4
Adrenal Gland (ADRENAL_GLAND)            36.0
Ampulla of Vater (AMPULLA_OF_VATER)      32.4
Cervix (CERVIX)                          12.6
Pleura (PLEURA)                          13.0
Thymus (THYMUS)                           8.0
VEP_germline                            654.0
dtype: float64
331.18222818131017 1.1621264315072151e-54 26

,Bowel (BOWEL),Esophagus/Stomach (STOMACH),Lung (LUNG),Breast (BREAST),Head and Neck (HEAD_NECK),Liver (LIVER),Ovary/Fallopian Tube (OVARY),Pancreas (PANCREAS),Lymphoid (LYMPH),CNS/Brain (BRAIN),...,Soft Tissue (SOFT_TISSUE),Kidney (KIDNEY),Bone (BONE),Other (OTHER),Adrenal Gland (ADRENAL_GLAND),Ampulla of Vater (AMPULLA_OF_VATER),Cervix (CERVIX),Pleura (PLEURA),Thymus (THYMUS),VEP_germline
0,,,,,,,,,,,,,,,,,,,,,
stop_gained,810.6,823.6,661.4,342.2,304.2,183.8,172.4,194.2,111.0,73.8,...,34.4,31.4,9.0,11.6,16.0,16.8,8.0,7.0,4.0,192.0
frameshift_variant,522.4,590.6,517.4,421.0,267.2,150.6,220.6,189.0,77.0,75.2,...,30.6,30.2,19.8,21.8,20.0,15.6,4.6,6.0,4.0,462.0

[[709.68194849 752.91238676 627.58670734 406.3235282  304.21025159
  178.03274087 209.23106208 204.01359539 100.09017728  79.32678944
  116.70088755 121.38595968  52.49410362  68.99833498  90.82651194
   80.7110153   37.2676192   34.6056464   32.7955049   15.33296333
   17.7819783   19.16620416  17.24958374   6.70817146   6.92112928
    4.25915648 348.18604224]
 [623.31805151 661.28761324 551.21329266 356.8764718  267.18974841
  156.36725913 183.76893792 179.18640461  87.90982272  69.67321056
  102.49911245 106.61404032  46.10589638  60.60166502  79.77348806
   70.8889847   32.7323808   30.3943536   28.8044951   13.46703667
   15.6180217   16.83379584  15.15041626   5.89182854   6.07887072
    3.74084352 305.81395776]]

,Bowel (BOWEL),Esophagus/Stomach (STOMACH),Lung (LUNG),Breast (BREAST),Head and Neck (HEAD_NECK),Liver (LIVER),Ovary/Fallopian Tube (OVARY),Pancreas (PANCREAS),Lymphoid (LYMPH),CNS/Brain (BRAIN),...,Soft Tissue (SOFT_TISSUE),Kidney (KIDNEY),Bone (BONE),Other (OTHER),Adrenal Gland (ADRENAL_GLAND),Ampulla of Vater (AMPULLA_OF_VATER),Cervix (CERVIX),Pleura (PLEURA),Thymus (THYMUS),VEP_germline
0,,,,,,,,,,,,,,,,,,,,,
stop_gained,6.018922,4.115786,2.122494,-4.870003,-0.000889,0.64457,-3.810436,-1.027582,1.612184,-0.915304,...,-0.051314,-0.357622,-2.36904,-2.147983,-1.059813,-0.158595,0.729923,0.043874,-0.183721,-12.72696
frameshift_variant,-6.018922,-4.115786,-2.122494,4.870003,0.000889,-0.64457,3.810436,1.027582,-1.612184,0.915304,...,0.051314,0.357622,2.36904,2.147983,1.059813,0.158595,-0.729923,-0.043874,0.183721,12.72696

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/TP53
70
62
62
20
82
37469

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
CNS/Brain (BRAIN)                   26
Esophagus/Stomach (STOMACH)         13
Lung (LUNG)                         12
Bowel (BOWEL)                       10
Bladder/Urinary Tract (BLADDER)      3
Skin (SKIN)                          2
Head and Neck (HEAD_NECK)            2
Soft Tissue (SOFT_TISSUE)            2
Pleura (PLEURA)                      2
Bone (BONE)                          2
Thyroid (THYROID)                    2
Pancreas (PANCREAS)                  1
Peritoneum (PERITONEUM)              1
Kidney (KIDNEY)                      1
Cervix (CERVIX)                      1
Liver (LIVER)                        1
Biliary Tract (BILIARY_TRACT)        1

                    CNS/Brain (BRAIN)  VEP_germline
0
stop_gained                       3.0          22.0
frameshift_variant               12.0          64.0

CNS/Brain (BRAIN)    15.0
VEP_germline         86.0
dtype: float64
0.019048245614035102 0.8902282609657444 1

                    CNS/Brain (BRAIN)  VEP_germline
0
stop_gained                       3.0          22.0
frameshift_variant               12.0          64.0

[[ 3.71287129 21.28712871]
 [11.28712871 64.71287129]]

                    CNS/Brain (BRAIN)  VEP_germline
0
stop_gained                 -0.462191      0.462191
frameshift_variant           0.462191     -0.462191

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/SUFU
566
521
521
267
787

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

38256

                                     count
parent_tissue_code
Lung (LUNG)                            550
Esophagus/Stomach (STOMACH)             42
Biliary Tract (BILIARY_TRACT)           41
Pancreas (PANCREAS)                     22
Cervix (CERVIX)                         22
Bowel (BOWEL)                           21
Breast (BREAST)                         19
Liver (LIVER)                           13
Other (OTHER)                           11
Thyroid (THYROID)                       10
Skin (SKIN)                              9
Uterus (UTERUS)                          9
Prostate (PROSTATE)                      3
Ovary/Fallopian Tube (OVARY)             3
Head and Neck (HEAD_NECK)                3
Ampulla of Vater (AMPULLA_OF_VATER)      2
Adrenal Gland (ADRENAL_GLAND)            1
Testis (TESTIS)                          1
Soft Tissue (SOFT_TISSUE)                1
Thymus (THYMUS)                          1
Kidney (KIDNEY)                          1
Bladder/Urinary Tract (BLADDER)          1
CNS/Brain (BRAIN)                        1

,Lung (LUNG),Esophagus/Stomach (STOMACH),Biliary Tract (BILIARY_TRACT),VEP_germline
0,,,,
stop_gained,169.4,8.0,10.2,90.0
frameshift_variant,173.6,17.0,19.0,180.0

Lung (LUNG)                      343.0
Esophagus/Stomach (STOMACH)       25.0
Biliary Tract (BILIARY_TRACT)     29.2
VEP_germline                     270.0
dtype: float64
17.639588251433693 0.0005219152099245341 3

,Lung (LUNG),Esophagus/Stomach (STOMACH),Biliary Tract (BILIARY_TRACT),VEP_germline
0,,,,
stop_gained,169.4,8.0,10.2,90.0
frameshift_variant,173.6,17.0,19.0,180.0

[[142.71103118  10.40167866  12.14916067 112.3381295 ]
 [200.28896882  14.59832134  17.05083933 157.6618705 ]]

,Lung (LUNG),Esophagus/Stomach (STOMACH),Biliary Tract (BILIARY_TRACT),VEP_germline
0,,,,
stop_gained,4.194142,-0.993287,-0.74836,-3.574581
frameshift_variant,-4.194142,0.993287,0.74836,3.574581

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/STK11
139
125
125
19
144
38400

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
CNS/Brain (BRAIN)                   38
Kidney (KIDNEY)                     34
Bowel (BOWEL)                       11
Esophagus/Stomach (STOMACH)         10
Pancreas (PANCREAS)                  9
Bladder/Urinary Tract (BLADDER)      7
Lung (LUNG)                          7
Liver (LIVER)                        4
Other (OTHER)                        4
Lymphoid (LYMPH)                     3
Breast (BREAST)                      3
Skin (SKIN)                          2
Head and Neck (HEAD_NECK)            2
Soft Tissue (SOFT_TISSUE)            2
Thyroid (THYROID)                    2
Uterus (UTERUS)                      2
Prostate (PROSTATE)                  1
Bone (BONE)                          1
Biliary Tract (BILIARY_TRACT)        1
Myeloid (MYELOID)                    1

                    CNS/Brain (BRAIN)  Kidney (KIDNEY)  VEP_germline
0
stop_gained                       9.0             17.0          19.0
frameshift_variant               25.0             12.0          23.0

CNS/Brain (BRAIN)    34.0
Kidney (KIDNEY)      29.0
VEP_germline         42.0
dtype: float64
6.767692134324995 0.03391675743338589 2

                    CNS/Brain (BRAIN)  Kidney (KIDNEY)  VEP_germline
0
stop_gained                       9.0             17.0          19.0
frameshift_variant               25.0             12.0          23.0

[[14.57142857 12.42857143 18.        ]
 [19.42857143 16.57142857 24.        ]]

                    CNS/Brain (BRAIN)  Kidney (KIDNEY)  VEP_germline
0
stop_gained                  -2.34801         2.016268      0.402538
frameshift_variant            2.34801        -2.016268     -0.402538

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/SMARCB1
457
395
395
257
650
39050

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                     count
parent_tissue_code
Lung (LUNG)                            208
Ovary/Fallopian Tube (OVARY)            72
Bowel (BOWEL)                           65
Esophagus/Stomach (STOMACH)             54
CNS/Brain (BRAIN)                       39
Lymphoid (LYMPH)                        35
Skin (SKIN)                             22
Bladder/Urinary Tract (BLADDER)         20
Pancreas (PANCREAS)                     20
Biliary Tract (BILIARY_TRACT)           16
Breast (BREAST)                         16
Kidney (KIDNEY)                         16
Liver (LIVER)                           15
Head and Neck (HEAD_NECK)               13
Other (OTHER)                            9
Uterus (UTERUS)                          7
Cervix (CERVIX)                          6
Ampulla of Vater (AMPULLA_OF_VATER)      4
Thyroid (THYROID)                        4
Prostate (PROSTATE)                      3
Thymus (THYMUS)                          2
Soft Tissue (SOFT_TISSUE)                2
Bone (BONE)                              1
Pleura (PLEURA)                          1

,Lung (LUNG),Ovary/Fallopian Tube (OVARY),Bowel (BOWEL),Esophagus/Stomach (STOMACH),CNS/Brain (BRAIN),Lymphoid (LYMPH),VEP_germline
0,,,,,,,
stop_gained,84.0,17.8,11.6,15.0,2.0,5.0,87.0
frameshift_variant,66.6,18.8,17.8,9.0,2.0,4.0,85.0

Lung (LUNG)                     150.6
Ovary/Fallopian Tube (OVARY)     36.6
Bowel (BOWEL)                    29.4
Esophagus/Stomach (STOMACH)      24.0
CNS/Brain (BRAIN)                 4.0
Lymphoid (LYMPH)                  9.0
VEP_germline                    172.0
dtype: float64
4.121753916296723 0.6602038268442636 6

,Lung (LUNG),Ovary/Fallopian Tube (OVARY),Bowel (BOWEL),Esophagus/Stomach (STOMACH),CNS/Brain (BRAIN),Lymphoid (LYMPH),VEP_germline
0,,,,,,,
stop_gained,84.0,17.8,11.6,15.0,2.0,5.0,87.0
frameshift_variant,66.6,18.8,17.8,9.0,2.0,4.0,85.0

[[78.69699248 19.12556391 15.36315789 12.54135338  2.09022556  4.70300752
  89.87969925]
 [71.90300752 17.47443609 14.03684211 11.45864662  1.90977444  4.29699248
  82.12030075]]

,Lung (LUNG),Ovary/Fallopian Tube (OVARY),Bowel (BOWEL),Esophagus/Stomach (STOMACH),CNS/Brain (BRAIN),Lymphoid (LYMPH),VEP_germline
0,,,,,,,
stop_gained,1.076259,-0.458837,-1.440107,1.034348,-0.090745,0.200326,-0.569484
frameshift_variant,-1.076259,0.458837,1.440107,-1.034348,0.090745,-0.200326,0.569484

FLAG5 = 1
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/SMARCA4

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

1356
1247
1247
541
1788
40838

                                     count
parent_tissue_code
Bowel (BOWEL)                          800
Pancreas (PANCREAS)                    360
Esophagus/Stomach (STOMACH)            181
Lung (LUNG)                            148
Biliary Tract (BILIARY_TRACT)          118
Breast (BREAST)                         47
Ampulla of Vater (AMPULLA_OF_VATER)     26
Head and Neck (HEAD_NECK)               18
Bladder/Urinary Tract (BLADDER)         15
Cervix (CERVIX)                         12
Other (OTHER)                           11
Liver (LIVER)                           10
Ovary/Fallopian Tube (OVARY)            10
Skin (SKIN)                             10
Prostate (PROSTATE)                      9
Thyroid (THYROID)                        5
Uterus (UTERUS)                          2
Kidney (KIDNEY)                          2
Myeloid (MYELOID)                        2
Pleura (PLEURA)                          1
Adrenal Gland (ADRENAL_GLAND)            1

,Bowel (BOWEL),Pancreas (PANCREAS),Esophagus/Stomach (STOMACH),Lung (LUNG),Biliary Tract (BILIARY_TRACT),Breast (BREAST),Ampulla of Vater (AMPULLA_OF_VATER),VEP_germline
0,,,,,,,,
stop_gained,153.4,107.6,37.6,39.8,39.2,13.2,8.6,78.0
frameshift_variant,85.6,112.0,28.4,28.8,30.0,7.0,4.0,175.0

Bowel (BOWEL)                          239.0
Pancreas (PANCREAS)                    219.6
Esophagus/Stomach (STOMACH)             66.0
Lung (LUNG)                             68.6
Biliary Tract (BILIARY_TRACT)           69.2
Breast (BREAST)                         20.2
Ampulla of Vater (AMPULLA_OF_VATER)     12.6
VEP_germline                           253.0
dtype: float64
64.32042978950786 2.0592567144323748e-11 7

,Bowel (BOWEL),Pancreas (PANCREAS),Esophagus/Stomach (STOMACH),Lung (LUNG),Biliary Tract (BILIARY_TRACT),Breast (BREAST),Ampulla of Vater (AMPULLA_OF_VATER),VEP_germline
0,,,,,,,,
stop_gained,153.4,107.6,37.6,39.8,39.2,13.2,8.6,78.0
frameshift_variant,85.6,112.0,28.4,28.8,30.0,7.0,4.0,175.0

[[120.33178654 110.56426914  33.22969838  34.5387471   34.84083527
   10.17030162   6.34385151 127.38051044]
 [118.66821346 109.03573086  32.77030162  34.0612529   34.35916473
   10.02969838   6.25614849 125.61948956]]

,Bowel (BOWEL),Pancreas (PANCREAS),Esophagus/Stomach (STOMACH),Lung (LUNG),Biliary Tract (BILIARY_TRACT),Breast (BREAST),Ampulla of Vater (AMPULLA_OF_VATER),VEP_germline
0,,,,,,,,
stop_gained,4.946727,-0.456402,1.115441,1.319092,1.088545,1.362825,1.279758,-7.251551
frameshift_variant,-4.946727,0.456402,-1.115441,-1.319092,-1.088545,-1.362825,-1.279758,7.251551

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/SMAD4
39
36
36
12
48
40886

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
Lung (LUNG)                         10
Liver (LIVER)                        8
Bowel (BOWEL)                        6
Esophagus/Stomach (STOMACH)          5
Soft Tissue (SOFT_TISSUE)            4
CNS/Brain (BRAIN)                    3
Prostate (PROSTATE)                  2
Biliary Tract (BILIARY_TRACT)        2
Bladder/Urinary Tract (BLADDER)      1
Pancreas (PANCREAS)                  1
Testis (TESTIS)                      1
Myeloid (MYELOID)                    1
Uterus (UTERUS)                      1
Head and Neck (HEAD_NECK)            1
Skin (SKIN)                          1
Thyroid (THYROID)                    1

Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/SDHA
1546
1435
1431
773
2152
43038

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                     count
parent_tissue_code
Lung (LUNG)                            691
Bladder/Urinary Tract (BLADDER)        194
Liver (LIVER)                          177
Breast (BREAST)                        128
Esophagus/Stomach (STOMACH)            116
CNS/Brain (BRAIN)                      113
Eye (EYE)                              112
Skin (SKIN)                            111
Lymphoid (LYMPH)                        62
Bowel (BOWEL)                           57
Head and Neck (HEAD_NECK)               48
Prostate (PROSTATE)                     46
Ovary/Fallopian Tube (OVARY)            39
Pancreas (PANCREAS)                     38
Uterus (UTERUS)                         36
Bone (BONE)                             34
Soft Tissue (SOFT_TISSUE)               33
Thyroid (THYROID)                       28
Biliary Tract (BILIARY_TRACT)           26
Cervix (CERVIX)                         19
Kidney (KIDNEY)                         10
Other (OTHER)                           10
Myeloid (MYELOID)                        7
Adrenal Gland (ADRENAL_GLAND)            6
Ampulla of Vater (AMPULLA_OF_VATER)      3
Vulva/Vagina (VULVA)                     3
Pleura (PLEURA)                          3
Thymus (THYMUS)                          2

,Lung (LUNG),Bladder/Urinary Tract (BLADDER),Liver (LIVER),Breast (BREAST),Esophagus/Stomach (STOMACH),CNS/Brain (BRAIN),Eye (EYE),Skin (SKIN),Lymphoid (LYMPH),Bowel (BOWEL),Head and Neck (HEAD_NECK),Prostate (PROSTATE),Ovary/Fallopian Tube (OVARY),Pancreas (PANCREAS),Uterus (UTERUS),Bone (BONE),Soft Tissue (SOFT_TISSUE),Thyroid (THYROID),Biliary Tract (BILIARY_TRACT),VEP_germline
0,,,,,,,,,,,,,,,,,,,,
stop_gained,278.2,84.0,70.0,47.6,52.0,42.0,48.4,63.2,33.0,22.4,24.4,11.0,10.0,13.0,13.8,9.0,6.0,18.0,9.4,272.0
frameshift_variant,220.0,57.2,46.2,48.0,38.0,40.4,29.0,9.4,19.8,17.0,14.6,21.0,16.6,14.0,11.2,17.0,17.0,6.0,7.0,432.0

Lung (LUNG)                        498.2
Bladder/Urinary Tract (BLADDER)    141.2
Liver (LIVER)                      116.2
Breast (BREAST)                     95.6
Esophagus/Stomach (STOMACH)         90.0
CNS/Brain (BRAIN)                   82.4
Eye (EYE)                           77.4
Skin (SKIN)                         72.6
Lymphoid (LYMPH)                    52.8
Bowel (BOWEL)                       39.4
Head and Neck (HEAD_NECK)           39.0
Prostate (PROSTATE)                 32.0
Ovary/Fallopian Tube (OVARY)        26.6
Pancreas (PANCREAS)                 27.0
Uterus (UTERUS)                     25.0
Bone (BONE)                         26.0
Soft Tissue (SOFT_TISSUE)           23.0
Thyroid (THYROID)                   24.0
Biliary Tract (BILIARY_TRACT)       16.4
VEP_germline                       704.0
dtype: float64
124.80781696836985 1.3911948768415642e-17 19

,Lung (LUNG),Bladder/Urinary Tract (BLADDER),Liver (LIVER),Breast (BREAST),Esophagus/Stomach (STOMACH),CNS/Brain (BRAIN),Eye (EYE),Skin (SKIN),Lymphoid (LYMPH),Bowel (BOWEL),Head and Neck (HEAD_NECK),Prostate (PROSTATE),Ovary/Fallopian Tube (OVARY),Pancreas (PANCREAS),Uterus (UTERUS),Bone (BONE),Soft Tissue (SOFT_TISSUE),Thyroid (THYROID),Biliary Tract (BILIARY_TRACT),VEP_germline
0,,,,,,,,,,,,,,,,,,,,
stop_gained,278.2,84.0,70.0,47.6,52.0,42.0,48.4,63.2,33.0,22.4,24.4,11.0,10.0,13.0,13.8,9.0,6.0,18.0,9.4,272.0
frameshift_variant,220.0,57.2,46.2,48.0,38.0,40.4,29.0,9.4,19.8,17.0,14.6,21.0,16.6,14.0,11.2,17.0,17.0,6.0,7.0,432.0

[[254.28770373  72.07030062  59.30997827  48.79547265  45.93716045
   42.05802246  39.50595799  37.0559761   26.9498008   20.11026802
   19.90610286  16.3332126   13.57698298  13.78114813  12.76032235
   13.27073524  11.73949656  12.24990945   8.37077146 359.33067729]
 [243.91229627  69.12969938  56.89002173  46.80452735  44.06283955
   40.34197754  37.89404201  35.5440239   25.8501992   19.28973198
   19.09389714  15.6667874   13.02301702  13.21885187  12.23967765
   12.72926476  11.26050344  11.75009055   8.02922854 344.66932271]]

,Lung (LUNG),Bladder/Urinary Tract (BLADDER),Liver (LIVER),Breast (BREAST),Esophagus/Stomach (STOMACH),CNS/Brain (BRAIN),Eye (EYE),Skin (SKIN),Lymphoid (LYMPH),Bowel (BOWEL),Head and Neck (HEAD_NECK),Prostate (PROSTATE),Ovary/Fallopian Tube (OVARY),Pancreas (PANCREAS),Uterus (UTERUS),Bone (BONE),Soft Tissue (SOFT_TISSUE),Thyroid (THYROID),Biliary Tract (BILIARY_TRACT),VEP_germline
0,,,,,,,,,,,,,,,,,,,,
stop_gained,2.435273,2.07578,2.038144,-0.250059,1.305306,-0.013032,2.058726,6.241451,1.685896,0.736324,1.45239,-1.899796,-1.395826,-0.302584,0.418335,-1.685433,-2.406617,2.360835,0.510308,-7.977072
frameshift_variant,-2.435273,-2.07578,-2.038144,0.250059,-1.305306,0.013032,-2.058726,-6.241451,-1.685896,-0.736324,-1.45239,1.899796,1.395826,0.302584,-0.418335,1.685433,2.406617,-2.360835,-0.510308,7.977072

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/RB1
2246
1900
1888
1948
3832
46870

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                     count
parent_tissue_code
Uterus (UTERUS)                       1355
CNS/Brain (BRAIN)                      400
Bowel (BOWEL)                          364
Breast (BREAST)                        300
Lung (LUNG)                            282
Skin (SKIN)                            143
Esophagus/Stomach (STOMACH)            142
Prostate (PROSTATE)                    134
Kidney (KIDNEY)                        126
Ovary/Fallopian Tube (OVARY)            87
Thyroid (THYROID)                       79
Liver (LIVER)                           78
Head and Neck (HEAD_NECK)               69
Lymphoid (LYMPH)                        67
Soft Tissue (SOFT_TISSUE)               52
Cervix (CERVIX)                         36
Pancreas (PANCREAS)                     30
Bladder/Urinary Tract (BLADDER)         26
Biliary Tract (BILIARY_TRACT)           19
Bone (BONE)                             15
Other (OTHER)                            7
Ampulla of Vater (AMPULLA_OF_VATER)      5
Myeloid (MYELOID)                        5
Pleura (PLEURA)                          4
Testis (TESTIS)                          3
Eye (EYE)                                2
Thymus (THYMUS)                          1
Vulva/Vagina (VULVA)                     1

,Uterus (UTERUS),CNS/Brain (BRAIN),Bowel (BOWEL),Breast (BREAST),Lung (LUNG),Skin (SKIN),Esophagus/Stomach (STOMACH),Prostate (PROSTATE),Kidney (KIDNEY),Ovary/Fallopian Tube (OVARY),Thyroid (THYROID),Liver (LIVER),Head and Neck (HEAD_NECK),Lymphoid (LYMPH),Soft Tissue (SOFT_TISSUE),Cervix (CERVIX),Pancreas (PANCREAS),Bladder/Urinary Tract (BLADDER),VEP_germline
0,,,,,,,,,,,,,,,,,,,
stop_gained,212.0,90.8,70.4,43.6,87.4,35.0,31.4,27.4,27.4,14.8,22.2,7.8,21.4,18.8,8.0,14.0,10.2,5.0,304.0
frameshift_variant,403.0,109.6,114.8,134.0,61.4,48.8,40.8,53.0,47.0,29.2,24.4,28.2,20.4,11.4,13.6,6.8,9.0,5.0,556.0

Uterus (UTERUS)                    615.0
CNS/Brain (BRAIN)                  200.4
Bowel (BOWEL)                      185.2
Breast (BREAST)                    177.6
Lung (LUNG)                        148.8
Skin (SKIN)                         83.8
Esophagus/Stomach (STOMACH)         72.2
Prostate (PROSTATE)                 80.4
Kidney (KIDNEY)                     74.4
Ovary/Fallopian Tube (OVARY)        44.0
Thyroid (THYROID)                   46.6
Liver (LIVER)                       36.0
Head and Neck (HEAD_NECK)           41.8
Lymphoid (LYMPH)                    30.2
Soft Tissue (SOFT_TISSUE)           21.6
Cervix (CERVIX)                     20.8
Pancreas (PANCREAS)                 19.2
Bladder/Urinary Tract (BLADDER)     10.0
VEP_germline                       860.0
dtype: float64
80.12470016697223 8.149290217740322e-10 18

,Uterus (UTERUS),CNS/Brain (BRAIN),Bowel (BOWEL),Breast (BREAST),Lung (LUNG),Skin (SKIN),Esophagus/Stomach (STOMACH),Prostate (PROSTATE),Kidney (KIDNEY),Ovary/Fallopian Tube (OVARY),Thyroid (THYROID),Liver (LIVER),Head and Neck (HEAD_NECK),Lymphoid (LYMPH),Soft Tissue (SOFT_TISSUE),Cervix (CERVIX),Pancreas (PANCREAS),Bladder/Urinary Tract (BLADDER),VEP_germline
0,,,,,,,,,,,,,,,,,,,
stop_gained,212.0,90.8,70.4,43.6,87.4,35.0,31.4,27.4,27.4,14.8,22.2,7.8,21.4,18.8,8.0,14.0,10.2,5.0,304.0
frameshift_variant,403.0,109.6,114.8,134.0,61.4,48.8,40.8,53.0,47.0,29.2,24.4,28.2,20.4,11.4,13.6,6.8,9.0,5.0,556.0

[[233.6466763   76.13462428  70.3599422   67.47260116  56.53109827
   31.8367341   27.42973988  30.5450289   28.26554913  16.71618497
   17.70395954  13.67687861  15.88037572  11.4733815    8.20612717
    7.90219653   7.29433526   3.79913295 326.72543353]
 [381.3533237  124.26537572 114.8400578  110.12739884  92.26890173
   51.9632659   44.77026012  49.8549711   46.13445087  27.28381503
   28.89604046  22.32312139  25.91962428  18.7266185   13.39387283
   12.89780347  11.90566474   6.20086705 533.27456647]]

,Uterus (UTERUS),CNS/Brain (BRAIN),Bowel (BOWEL),Breast (BREAST),Lung (LUNG),Skin (SKIN),Esophagus/Stomach (STOMACH),Prostate (PROSTATE),Kidney (KIDNEY),Ovary/Fallopian Tube (OVARY),Thyroid (THYROID),Liver (LIVER),Head and Neck (HEAD_NECK),Lymphoid (LYMPH),Soft Tissue (SOFT_TISSUE),Cervix (CERVIX),Pancreas (PANCREAS),Bladder/Urinary Tract (BLADDER),VEP_germline
0,,,,,,,,,,,,,,,,,,,
stop_gained,-2.039136,2.21613,0.006278,-3.815131,5.359817,0.722971,0.975486,-0.73338,-0.209582,-0.59996,1.368534,-2.03128,1.772381,2.761937,-0.091736,2.765102,1.371001,0.783813,-1.92304
frameshift_variant,2.039136,-2.21613,-0.006278,3.815131,-5.359817,-0.722971,-0.975486,0.73338,0.209582,0.59996,-1.368534,2.03128,-1.772381,-2.761937,0.091736,-2.765102,-1.371001,-0.783813,1.92304

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/PTEN
224
196
195
280
475
47345

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
Skin (SKIN)                        184
CNS/Brain (BRAIN)                   94
Esophagus/Stomach (STOMACH)         74
Bowel (BOWEL)                       60
Lung (LUNG)                         18
Head and Neck (HEAD_NECK)            9
Liver (LIVER)                        6
Pleura (PLEURA)                      5
Soft Tissue (SOFT_TISSUE)            4
Uterus (UTERUS)                      4
Breast (BREAST)                      3
Kidney (KIDNEY)                      3
Ovary/Fallopian Tube (OVARY)         3
Lymphoid (LYMPH)                     2
Biliary Tract (BILIARY_TRACT)        2
Bladder/Urinary Tract (BLADDER)      1
Other (OTHER)                        1
Prostate (PROSTATE)                  1
Bone (BONE)                          1

,Skin (SKIN),CNS/Brain (BRAIN),Esophagus/Stomach (STOMACH),Bowel (BOWEL),VEP_germline
0,,,,,
stop_gained,94.4,12.8,19.0,13.0,174.0
frameshift_variant,45.6,64.8,46.0,46.0,333.0

Skin (SKIN)                    140.0
CNS/Brain (BRAIN)               77.6
Esophagus/Stomach (STOMACH)     65.0
Bowel (BOWEL)                   59.0
VEP_germline                   507.0
dtype: float64
78.59999638013211 3.447725443513896e-16 4

,Skin (SKIN),CNS/Brain (BRAIN),Esophagus/Stomach (STOMACH),Bowel (BOWEL),VEP_germline
0,,,,,
stop_gained,94.4,12.8,19.0,13.0,174.0
frameshift_variant,45.6,64.8,46.0,46.0,333.0

[[ 51.67098751  28.64049022  23.99010134  21.77563045 187.12279048]
 [ 88.32901249  48.95950978  41.00989866  37.22436955 319.87720952]]

,Skin (SKIN),CNS/Brain (BRAIN),Esophagus/Stomach (STOMACH),Bowel (BOWEL),VEP_germline
0,,,,,
stop_gained,8.189601,-3.909444,-1.334781,-2.454445,-1.903565
frameshift_variant,-8.189601,3.909444,1.334781,2.454445,1.903565

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/PTCH1
91
83
82
42
123
47468

                                 count
parent_tissue_code
Bowel (BOWEL)                       40
Lung (LUNG)                         18
Esophagus/Stomach (STOMACH)         15
Breast (BREAST)                      8
Pancreas (PANCREAS)                  7
Kidney (KIDNEY)                      6
Prostate (PROSTATE)                  5
Ovary/Fallopian Tube (OVARY)         4
Liver (LIVER)                        4
Biliary Tract (BILIARY_TRACT)        4
Skin (SKIN)                          4
Head and Neck (HEAD_NECK)            2
CNS/Brain (BRAIN)                    1
Bladder/Urinary Tract (BLADDER)      1
Lymphoid (LYMPH)                     1
Uterus (UTERUS)                      1
Thyroid (THYROID)                    1
Soft Tissue (SOFT_TISSUE)            1

                    Bowel (BOWEL)  VEP_germline
0
stop_gained                   5.0         761.0
frameshift_variant           33.0        1499.0

Bowel (BOWEL)      38.0
VEP_germline     2260.0
dtype: float64
6.184504541220306 0.01288737821340346 1

                    Bowel (BOWEL)  VEP_germline
0
stop_gained                   5.0         761.0
frameshift_variant           33.0        1499.0

[[  12.66666667  753.33333333]
 [  25.33333333 1506.66666667]]

                    Bowel (BOWEL)  VEP_germline
0
stop_gained             -2.660369      2.660369
frameshift_variant       2.660369     -2.660369

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/PALB2
326
243
243

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

656
899
48367

                                 count
parent_tissue_code
CNS/Brain (BRAIN)                  393
Pleura (PLEURA)                    119
Peripheral Nervous System (PNS)     88
Kidney (KIDNEY)                     71
Lung (LUNG)                         36
Thyroid (THYROID)                   30
Skin (SKIN)                         20
Esophagus/Stomach (STOMACH)         19
Bowel (BOWEL)                       16
Liver (LIVER)                       14
Breast (BREAST)                     12
Soft Tissue (SOFT_TISSUE)           12
Bladder/Urinary Tract (BLADDER)     11
Head and Neck (HEAD_NECK)            9
Ovary/Fallopian Tube (OVARY)         9
Cervix (CERVIX)                      8
Other (OTHER)                        8
Bone (BONE)                          6
Peritoneum (PERITONEUM)              4
Biliary Tract (BILIARY_TRACT)        3
Pancreas (PANCREAS)                  3
Thymus (THYMUS)                      2
Lymphoid (LYMPH)                     2
Adrenal Gland (ADRENAL_GLAND)        2
Uterus (UTERUS)                      1
Testis (TESTIS)                      1

,CNS/Brain (BRAIN),Pleura (PLEURA),Peripheral Nervous System (PNS),Kidney (KIDNEY),Lung (LUNG),Thyroid (THYROID),VEP_germline
0,,,,,,,
stop_gained,89.0,73.0,26.0,24.0,19.0,17.6,106.0
frameshift_variant,209.0,24.2,39.8,35.0,5.0,5.4,73.0

CNS/Brain (BRAIN)                  298.0
Pleura (PLEURA)                     97.2
Peripheral Nervous System (PNS)     65.8
Kidney (KIDNEY)                     59.0
Lung (LUNG)                         24.0
Thyroid (THYROID)                   23.0
VEP_germline                       179.0
dtype: float64
96.9098892883291 1.1062464662021298e-18 6

,CNS/Brain (BRAIN),Pleura (PLEURA),Peripheral Nervous System (PNS),Kidney (KIDNEY),Lung (LUNG),Thyroid (THYROID),VEP_germline
0,,,,,,,
stop_gained,89.0,73.0,26.0,24.0,19.0,17.6,106.0
frameshift_variant,209.0,24.2,39.8,35.0,5.0,5.4,73.0

[[141.64986595  46.20257373  31.27705094  28.04477212  11.4080429
   10.93270777  85.0849866 ]
 [156.35013405  50.99742627  34.52294906  30.95522788  12.5919571
   12.06729223  93.9150134 ]]

,CNS/Brain (BRAIN),Pleura (PLEURA),Peripheral Nervous System (PNS),Kidney (KIDNEY),Lung (LUNG),Thyroid (THYROID),VEP_germline
0,,,,,,,
stop_gained,-7.88095,5.836238,-1.364233,-1.098799,3.154336,2.827775,3.590613
frameshift_variant,7.88095,-5.836238,1.364233,1.098799,-3.154336,-2.827775,-3.590613

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/NF2
1107
967
967
795
1760
50127

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                     count
parent_tissue_code
Lung (LUNG)                            234
CNS/Brain (BRAIN)                      225
Peripheral Nervous System (PNS)        182
Skin (SKIN)                            178
Myeloid (MYELOID)                      162
Breast (BREAST)                        146
Bowel (BOWEL)                          104
Esophagus/Stomach (STOMACH)             73
Ovary/Fallopian Tube (OVARY)            66
Soft Tissue (SOFT_TISSUE)               54
Liver (LIVER)                           49
Lymphoid (LYMPH)                        45
Adrenal Gland (ADRENAL_GLAND)           42
Head and Neck (HEAD_NECK)               33
Thyroid (THYROID)                       32
Biliary Tract (BILIARY_TRACT)           30
Bladder/Urinary Tract (BLADDER)         27
Uterus (UTERUS)                         19
Kidney (KIDNEY)                         13
Other (OTHER)                           10
Pancreas (PANCREAS)                      9
Prostate (PROSTATE)                      5
Cervix (CERVIX)                          5
Ampulla of Vater (AMPULLA_OF_VATER)      4
Vulva/Vagina (VULVA)                     4
Bone (BONE)                              4
Thymus (THYMUS)                          2
Testis (TESTIS)                          2
Pleura (PLEURA)                          1

,Lung (LUNG),CNS/Brain (BRAIN),Peripheral Nervous System (PNS),Skin (SKIN),Myeloid (MYELOID),Breast (BREAST),Bowel (BOWEL),Esophagus/Stomach (STOMACH),Ovary/Fallopian Tube (OVARY),Soft Tissue (SOFT_TISSUE),Liver (LIVER),Lymphoid (LYMPH),Adrenal Gland (ADRENAL_GLAND),Head and Neck (HEAD_NECK),Thyroid (THYROID),Biliary Tract (BILIARY_TRACT),Bladder/Urinary Tract (BLADDER),VEP_germline
0,,,,,,,,,,,,,,,,,,
stop_gained,86.6,67.0,29.4,80.6,57.4,58.0,27.2,29.4,23.4,18.0,11.6,11.6,9.8,12.0,13.0,16.0,15.6,1585.0
frameshift_variant,67.4,85.2,39.8,22.6,60.2,52.0,45.6,20.0,25.0,28.0,16.8,14.4,23.2,10.6,14.0,7.6,1.4,2900.0

Lung (LUNG)                         154.0
CNS/Brain (BRAIN)                   152.2
Peripheral Nervous System (PNS)      69.2
Skin (SKIN)                         103.2
Myeloid (MYELOID)                   117.6
Breast (BREAST)                     110.0
Bowel (BOWEL)                        72.8
Esophagus/Stomach (STOMACH)          49.4
Ovary/Fallopian Tube (OVARY)         48.4
Soft Tissue (SOFT_TISSUE)            46.0
Liver (LIVER)                        28.4
Lymphoid (LYMPH)                     26.0
Adrenal Gland (ADRENAL_GLAND)        33.0
Head and Neck (HEAD_NECK)            22.6
Thyroid (THYROID)                    27.0
Biliary Tract (BILIARY_TRACT)        23.6
Bladder/Urinary Tract (BLADDER)      17.0
VEP_germline                       4485.0
dtype: float64
169.60990010726348 3.352178133206649e-27 17

,Lung (LUNG),CNS/Brain (BRAIN),Peripheral Nervous System (PNS),Skin (SKIN),Myeloid (MYELOID),Breast (BREAST),Bowel (BOWEL),Esophagus/Stomach (STOMACH),Ovary/Fallopian Tube (OVARY),Soft Tissue (SOFT_TISSUE),Liver (LIVER),Lymphoid (LYMPH),Adrenal Gland (ADRENAL_GLAND),Head and Neck (HEAD_NECK),Thyroid (THYROID),Biliary Tract (BILIARY_TRACT),Bladder/Urinary Tract (BLADDER),VEP_germline
0,,,,,,,,,,,,,,,,,,
stop_gained,86.6,67.0,29.4,80.6,57.4,58.0,27.2,29.4,23.4,18.0,11.6,11.6,9.8,12.0,13.0,16.0,15.6,1585.0
frameshift_variant,67.4,85.2,39.8,22.6,60.2,52.0,45.6,20.0,25.0,28.0,16.8,14.4,23.2,10.6,14.0,7.6,1.4,2900.0

[[  59.32366527   58.63027178   26.65712751   39.7545601    45.30170802
    42.37404662   28.04391449   19.02979912   18.64458051   17.72005586
    10.9402084    10.01568375   12.71221399    8.70594049   10.40090235
     9.09115909    6.5487163  1727.70544634]
 [  94.67633473   93.56972822   42.54287249   63.4454399    72.29829198
    67.62595338   44.75608551   30.37020088   29.75541949   28.27994414
    17.4597916    15.98431625   20.28778601   13.89405951   16.59909765
    14.50884091   10.4512837  2757.29455366]]

,Lung (LUNG),CNS/Brain (BRAIN),Peripheral Nervous System (PNS),Skin (SKIN),Myeloid (MYELOID),Breast (BREAST),Bowel (BOWEL),Esophagus/Stomach (STOMACH),Ovary/Fallopian Tube (OVARY),Soft Tissue (SOFT_TISSUE),Liver (LIVER),Lymphoid (LYMPH),Adrenal Gland (ADRENAL_GLAND),Head and Neck (HEAD_NECK),Thyroid (THYROID),Biliary Tract (BILIARY_TRACT),Bladder/Urinary Tract (BLADDER),VEP_germline
0,,,,,,,,,,,,,,,,,,
stop_gained,4.580184,1.413479,0.681782,8.339489,2.317006,3.092113,-0.204582,3.045361,1.410724,0.085168,0.255059,0.639962,-1.044814,1.426736,1.030336,2.928564,4.517869,-9.865002
frameshift_variant,-4.580184,-1.413479,-0.681782,-8.339489,-2.317006,-3.092113,0.204582,-3.045361,-1.410724,-0.085168,-0.255059,-0.639962,1.044814,-1.426736,-1.030336,-2.928564,-4.517869,9.865002

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/NF1
143
103
103
212
315
50442

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                     count
parent_tissue_code
Bowel (BOWEL)                          142
Esophagus/Stomach (STOMACH)             45
Lung (LUNG)                             20
Uterus (UTERUS)                         19
Skin (SKIN)                             15
Lymphoid (LYMPH)                        13
Liver (LIVER)                            7
Kidney (KIDNEY)                          7
Breast (BREAST)                          6
CNS/Brain (BRAIN)                        6
Head and Neck (HEAD_NECK)                5
Pancreas (PANCREAS)                      5
Prostate (PROSTATE)                      4
Ovary/Fallopian Tube (OVARY)             4
Bladder/Urinary Tract (BLADDER)          3
Thyroid (THYROID)                        3
Adrenal Gland (ADRENAL_GLAND)            2
Other (OTHER)                            2
Biliary Tract (BILIARY_TRACT)            2
Soft Tissue (SOFT_TISSUE)                1
Penis (PENIS)                            1
Cervix (CERVIX)                          1
Ampulla of Vater (AMPULLA_OF_VATER)      1
Testis (TESTIS)                          1

                    Bowel (BOWEL)  Esophagus/Stomach (STOMACH)  VEP_germline
0
stop_gained                  29.2                          3.0         835.0
frameshift_variant          100.8                         38.0        2174.0

Bowel (BOWEL)                   130.0
Esophagus/Stomach (STOMACH)      41.0
VEP_germline                   3009.0
dtype: float64
10.09504142002126 0.006425243757496014 2

                    Bowel (BOWEL)  Esophagus/Stomach (STOMACH)  VEP_germline
0
stop_gained                  29.2                          3.0         835.0
frameshift_variant          100.8                         38.0        2174.0

[[  35.45157233   11.1808805   820.56754717]
 [  94.54842767   29.8191195  2188.43245283]]

                    Bowel (BOWEL)  Esophagus/Stomach (STOMACH)  VEP_germline
0
stop_gained             -1.257128                    -2.887516      2.547669
frameshift_variant       1.257128                     2.887516     -2.547669

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/MSH6
109
63
63
138
201
50643

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
Bowel (BOWEL)                      102
Uterus (UTERUS)                     21
Lung (LUNG)                         13
Esophagus/Stomach (STOMACH)          8
Biliary Tract (BILIARY_TRACT)        8
Thyroid (THYROID)                    8
Lymphoid (LYMPH)                     7
Ovary/Fallopian Tube (OVARY)         5
Skin (SKIN)                          5
Adrenal Gland (ADRENAL_GLAND)        4
Prostate (PROSTATE)                  4
Kidney (KIDNEY)                      3
Pancreas (PANCREAS)                  3
Breast (BREAST)                      2
CNS/Brain (BRAIN)                    2
Bladder/Urinary Tract (BLADDER)      2
Bone (BONE)                          1
Soft Tissue (SOFT_TISSUE)            1
Pleura (PLEURA)                      1
Head and Neck (HEAD_NECK)            1

                    Bowel (BOWEL)  VEP_germline
0
stop_gained                  43.6         757.0
frameshift_variant           30.4        1539.0

Bowel (BOWEL)      74.0
VEP_germline     2296.0
dtype: float64
20.434439649288393 6.1709239568124034e-06 1

                    Bowel (BOWEL)  VEP_germline
0
stop_gained                  43.6         757.0
frameshift_variant           30.4        1539.0

[[  24.99763713  775.60236287]
 [  49.00236287 1520.39763713]]

                    Bowel (BOWEL)  VEP_germline
0
stop_gained              4.645305     -4.645305
frameshift_variant      -4.645305      4.645305

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/MSH2
99
78
78
133
211
50854

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
Bowel (BOWEL)                      113
Esophagus/Stomach (STOMACH)         18
Lung (LUNG)                         15
Skin (SKIN)                         11
Kidney (KIDNEY)                     10
Uterus (UTERUS)                      7
Ovary/Fallopian Tube (OVARY)         7
Bladder/Urinary Tract (BLADDER)      4
Head and Neck (HEAD_NECK)            4
CNS/Brain (BRAIN)                    3
Lymphoid (LYMPH)                     3
Thyroid (THYROID)                    3
Pancreas (PANCREAS)                  2
Liver (LIVER)                        2
Adrenal Gland (ADRENAL_GLAND)        2
Cervix (CERVIX)                      2
Prostate (PROSTATE)                  1
Biliary Tract (BILIARY_TRACT)        1
Pleura (PLEURA)                      1
Breast (BREAST)                      1
Thymus (THYMUS)                      1

                    Bowel (BOWEL)  VEP_germline
0
stop_gained                  27.4         516.0
frameshift_variant           41.6        1176.0

Bowel (BOWEL)      69.0
VEP_germline     1692.0
dtype: float64
2.223689677116478 0.13590791676186315 1

                    Bowel (BOWEL)  VEP_germline
0
stop_gained                  27.4         516.0
frameshift_variant           41.6        1176.0

[[  21.29165247  522.10834753]
 [  47.70834753 1169.89165247]]

                    Bowel (BOWEL)  VEP_germline
0
stop_gained              1.624149     -1.624149
frameshift_variant      -1.624149      1.624149

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/MLH1
229
214
213
92
305
51159

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                     count
parent_tissue_code
Pancreas (PANCREAS)                    111
Breast (BREAST)                         32
Lung (LUNG)                             27
Thyroid (THYROID)                       22
Esophagus/Stomach (STOMACH)             19
Bowel (BOWEL)                           18
Adrenal Gland (ADRENAL_GLAND)           16
Skin (SKIN)                             13
Liver (LIVER)                            8
Head and Neck (HEAD_NECK)                6
Soft Tissue (SOFT_TISSUE)                5
Kidney (KIDNEY)                          5
CNS/Brain (BRAIN)                        5
Bladder/Urinary Tract (BLADDER)          5
Prostate (PROSTATE)                      4
Bone (BONE)                              2
Biliary Tract (BILIARY_TRACT)            2
Other (OTHER)                            1
Ampulla of Vater (AMPULLA_OF_VATER)      1
Uterus (UTERUS)                          1
Pleura (PLEURA)                          1
Thymus (THYMUS)                          1

,Pancreas (PANCREAS),Breast (BREAST),Lung (LUNG),VEP_germline
0,,,,
stop_gained,27.0,7.0,6.0,183.0
frameshift_variant,61.0,23.0,17.0,349.0

Pancreas (PANCREAS)     88.0
Breast (BREAST)         30.0
Lung (LUNG)             23.0
VEP_germline           532.0
dtype: float64
2.438907766843606 0.48643305038642126 3

,Pancreas (PANCREAS),Breast (BREAST),Lung (LUNG),VEP_germline
0,,,,
stop_gained,27.0,7.0,6.0,183.0
frameshift_variant,61.0,23.0,17.0,349.0

[[ 29.1589896    9.94056464   7.62109955 176.27934621]
 [ 58.8410104   20.05943536  15.37890045 355.72065379]]

,Pancreas (PANCREAS),Breast (BREAST),Lung (LUNG),VEP_germline
0,,,,
stop_gained,-0.524439,-1.166886,-0.730723,1.352415
frameshift_variant,0.524439,1.166886,0.730723,-1.352415

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/MEN1
51
43
43

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

33
76
51235

                                 count
parent_tissue_code
Lung (LUNG)                         21
Uterus (UTERUS)                     17
Soft Tissue (SOFT_TISSUE)            8
Kidney (KIDNEY)                      5
Lymphoid (LYMPH)                     5
Breast (BREAST)                      4
Adrenal Gland (ADRENAL_GLAND)        4
Bowel (BOWEL)                        3
Skin (SKIN)                          2
Esophagus/Stomach (STOMACH)          2
Other (OTHER)                        1
CNS/Brain (BRAIN)                    1
Thyroid (THYROID)                    1
Testis (TESTIS)                      1
Bladder/Urinary Tract (BLADDER)      1

Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/MAX
87
68
68
47
115
51350

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
Bowel (BOWEL)                       40
Esophagus/Stomach (STOMACH)         28
Lung (LUNG)                         17
Liver (LIVER)                       10
Kidney (KIDNEY)                      4
Thyroid (THYROID)                    3
Lymphoid (LYMPH)                     2
Head and Neck (HEAD_NECK)            2
CNS/Brain (BRAIN)                    1
Pancreas (PANCREAS)                  1
Breast (BREAST)                      1
Pleura (PLEURA)                      1
Soft Tissue (SOFT_TISSUE)            1
Skin (SKIN)                          1
Bladder/Urinary Tract (BLADDER)      1
Adrenal Gland (ADRENAL_GLAND)        1
Thymus (THYMUS)                      1

                    Bowel (BOWEL)  Esophagus/Stomach (STOMACH)  VEP_germline
0
stop_gained                   5.0                          0.0         156.0
frameshift_variant           29.0                         23.0         362.0

Bowel (BOWEL)                   34.0
Esophagus/Stomach (STOMACH)     23.0
VEP_germline                   518.0
dtype: float64
13.0753427497125 0.0014478560906667829 2

                    Bowel (BOWEL)  Esophagus/Stomach (STOMACH)  VEP_germline
0
stop_gained                   5.0                          0.0         156.0
frameshift_variant           29.0                         23.0         362.0

[[  9.52   6.44 145.04]
 [ 24.48  16.56 372.96]]

                    Bowel (BOWEL)  Esophagus/Stomach (STOMACH)  VEP_germline
0
stop_gained             -1.786981                    -2.857133      3.290484
frameshift_variant       1.786981                     2.857133     -3.290484

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/FLCN
26
26
25
12
36

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

51386

                             count
parent_tissue_code
Lung (LUNG)                      8
Kidney (KIDNEY)                  8
Bowel (BOWEL)                    6
Pancreas (PANCREAS)              3
Esophagus/Stomach (STOMACH)      3
Liver (LIVER)                    2
Skin (SKIN)                      2
Head and Neck (HEAD_NECK)        1
Soft Tissue (SOFT_TISSUE)        1
Thyroid (THYROID)                1
CNS/Brain (BRAIN)                1

Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/FH
138
109
109
179
288
51674

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
Ovary/Fallopian Tube (OVARY)        69
Uterus (UTERUS)                     41
Bowel (BOWEL)                       31
Soft Tissue (SOFT_TISSUE)           26
Lung (LUNG)                         20
Thyroid (THYROID)                   20
Esophagus/Stomach (STOMACH)         12
Skin (SKIN)                         11
CNS/Brain (BRAIN)                   10
Head and Neck (HEAD_NECK)            9
Lymphoid (LYMPH)                     8
Bladder/Urinary Tract (BLADDER)      6
Breast (BREAST)                      5
Prostate (PROSTATE)                  5
Liver (LIVER)                        3
Kidney (KIDNEY)                      3
Cervix (CERVIX)                      2
Biliary Tract (BILIARY_TRACT)        1
Pleura (PLEURA)                      1
Adrenal Gland (ADRENAL_GLAND)        1
Peripheral Nervous System (PNS)      1
Thymus (THYMUS)                      1
Eye (EYE)                            1
Testis (TESTIS)                      1

,Ovary/Fallopian Tube (OVARY),Uterus (UTERUS),Bowel (BOWEL),Soft Tissue (SOFT_TISSUE),VEP_germline
0,,,,,
stop_gained,2.4,4.6,14.2,1.8,287.0
frameshift_variant,2.0,4.0,8.0,2.2,505.0

Ovary/Fallopian Tube (OVARY)      4.4
Uterus (UTERUS)                   8.6
Bowel (BOWEL)                    22.2
Soft Tissue (SOFT_TISSUE)         4.0
VEP_germline                    792.0
dtype: float64
8.756217143531577 0.06749027092122485 4

,Ovary/Fallopian Tube (OVARY),Uterus (UTERUS),Bowel (BOWEL),Soft Tissue (SOFT_TISSUE),VEP_germline
0,,,,,
stop_gained,2.4,4.6,14.2,1.8,287.0
frameshift_variant,2.0,4.0,8.0,2.2,505.0

[[  1.64100096   3.20741097   8.27959577   1.49181906 295.38017324]
 [  2.75899904   5.39258903  13.92040423   2.50818094 496.61982676]]

,Ovary/Fallopian Tube (OVARY),Uterus (UTERUS),Bowel (BOWEL),Soft Tissue (SOFT_TISSUE),VEP_germline
0,,,,,
stop_gained,0.750222,0.987085,2.633758,0.319408,-2.835454
frameshift_variant,-0.750222,-0.987085,-2.633758,-0.319408,2.835454

FLAG5 = 1
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/DICER1
72
61
61

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

68
129
51803

                               count
parent_tissue_code
Head and Neck (HEAD_NECK)         31
Bowel (BOWEL)                     21
Lymphoid (LYMPH)                  19
Lung (LUNG)                       16
Esophagus/Stomach (STOMACH)       13
Skin (SKIN)                       10
Thymus (THYMUS)                    8
Kidney (KIDNEY)                    3
Pancreas (PANCREAS)                2
Biliary Tract (BILIARY_TRACT)      1
Liver (LIVER)                      1
Cervix (CERVIX)                    1
CNS/Brain (BRAIN)                  1
Thyroid (THYROID)                  1
Eye (EYE)                          1

                    Head and Neck (HEAD_NECK)  VEP_germline
0
stop_gained                              16.0          15.0
frameshift_variant                       12.0          19.0

Head and Neck (HEAD_NECK)    28.0
VEP_germline                 34.0
dtype: float64
0.5861344537815126 0.4439178064620011 1

                    Head and Neck (HEAD_NECK)  VEP_germline
0
stop_gained                              16.0          15.0
frameshift_variant                       12.0          19.0

[[14. 17.]
 [14. 17.]]

                    Head and Neck (HEAD_NECK)  VEP_germline
0
stop_gained                          1.020792     -1.020792
frameshift_variant                  -1.020792      1.020792

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/CYLD
84
74
74
56
130
51933

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
Bowel (BOWEL)                       27
Lung (LUNG)                         21
Esophagus/Stomach (STOMACH)         20
Lymphoid (LYMPH)                     9
Bladder/Urinary Tract (BLADDER)      9
Ovary/Fallopian Tube (OVARY)         6
Kidney (KIDNEY)                      6
Head and Neck (HEAD_NECK)            6
Breast (BREAST)                      6
Uterus (UTERUS)                      3
CNS/Brain (BRAIN)                    3
Thyroid (THYROID)                    3
Liver (LIVER)                        2
Skin (SKIN)                          2
Soft Tissue (SOFT_TISSUE)            1
Pleura (PLEURA)                      1
Other (OTHER)                        1
Adrenal Gland (ADRENAL_GLAND)        1
Cervix (CERVIX)                      1
Thymus (THYMUS)                      1
Peritoneum (PERITONEUM)              1

                    Bowel (BOWEL)  VEP_germline
0
stop_gained                   9.0         322.0
frameshift_variant           13.0         745.0

Bowel (BOWEL)      22.0
VEP_germline     1067.0
dtype: float64
0.7208715007034935 0.3958581898521657 1

                    Bowel (BOWEL)  VEP_germline
0
stop_gained                   9.0         322.0
frameshift_variant           13.0         745.0

[[  6.68686869 324.31313131]
 [ 15.31313131 742.68686869]]

                    Bowel (BOWEL)  VEP_germline
0
stop_gained              1.083178     -1.083178
frameshift_variant      -1.083178      1.083178

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/CHEK2
66
62
62

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

822
884
52817

                                 count
parent_tissue_code
Myeloid (MYELOID)                  847
Lung (LUNG)                          9
Esophagus/Stomach (STOMACH)          9
Bowel (BOWEL)                        4
Lymphoid (LYMPH)                     4
Prostate (PROSTATE)                  3
Ovary/Fallopian Tube (OVARY)         3
Liver (LIVER)                        2
CNS/Brain (BRAIN)                    1
Bladder/Urinary Tract (BLADDER)      1
Kidney (KIDNEY)                      1

                    Myeloid (MYELOID)  VEP_germline
0
stop_gained                      21.0           8.0
frameshift_variant              552.2          20.0

Myeloid (MYELOID)    573.2
VEP_germline          28.0
dtype: float64
30.85373951406428 2.7822548266756346e-08 1

                    Myeloid (MYELOID)  VEP_germline
0
stop_gained                      21.0           8.0
frameshift_variant              552.2          20.0

[[ 27.64936793   1.35063207]
 [545.55063207  26.64936793]]

                    Myeloid (MYELOID)  VEP_germline
0
stop_gained                 -6.006255      6.006255
frameshift_variant           6.006255     -6.006255

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/CEBPA
1209
1141
1141
972
2113
54930

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                     count
parent_tissue_code
Lung (LUNG)                            361
Esophagus/Stomach (STOMACH)            321
Head and Neck (HEAD_NECK)              317
Skin (SKIN)                            316
Pancreas (PANCREAS)                    310
Biliary Tract (BILIARY_TRACT)           66
Lymphoid (LYMPH)                        64
Liver (LIVER)                           63
Bladder/Urinary Tract (BLADDER)         42
Bowel (BOWEL)                           35
Thyroid (THYROID)                       31
Breast (BREAST)                         27
Other (OTHER)                           26
CNS/Brain (BRAIN)                       22
Ovary/Fallopian Tube (OVARY)            18
Ampulla of Vater (AMPULLA_OF_VATER)     17
Soft Tissue (SOFT_TISSUE)               15
Uterus (UTERUS)                         11
Myeloid (MYELOID)                       10
Thymus (THYMUS)                          9
Bone (BONE)                              8
Cervix (CERVIX)                          8
Kidney (KIDNEY)                          8
Peripheral Nervous System (PNS)          2
Penis (PENIS)                            1
Peritoneum (PERITONEUM)                  1
Adrenal Gland (ADRENAL_GLAND)            1
Eye (EYE)                                1
Pleura (PLEURA)                          1
Prostate (PROSTATE)                      1

,Lung (LUNG),Esophagus/Stomach (STOMACH),Head and Neck (HEAD_NECK),Skin (SKIN),Pancreas (PANCREAS),Biliary Tract (BILIARY_TRACT),Lymphoid (LYMPH),Liver (LIVER),Bladder/Urinary Tract (BLADDER),Bowel (BOWEL),Thyroid (THYROID),Breast (BREAST),Other (OTHER),VEP_germline
0,,,,,,,,,,,,,,
stop_gained,120.6,106.2,164.0,157.0,83.0,24.0,43.8,24.0,12.0,15.0,14.0,10.0,12.4,41.0
frameshift_variant,123.8,121.6,51.0,42.4,162.2,17.0,8.0,16.0,13.4,9.0,11.0,9.0,5.4,77.0

Lung (LUNG)                        244.4
Esophagus/Stomach (STOMACH)        227.8
Head and Neck (HEAD_NECK)          215.0
Skin (SKIN)                        199.4
Pancreas (PANCREAS)                245.2
Biliary Tract (BILIARY_TRACT)       41.0
Lymphoid (LYMPH)                    51.8
Liver (LIVER)                       40.0
Bladder/Urinary Tract (BLADDER)     25.4
Bowel (BOWEL)                       24.0
Thyroid (THYROID)                   25.0
Breast (BREAST)                     19.0
Other (OTHER)                       17.8
VEP_germline                       118.0
dtype: float64
180.07232906726387 1.6402610520543044e-31 13

,Lung (LUNG),Esophagus/Stomach (STOMACH),Head and Neck (HEAD_NECK),Skin (SKIN),Pancreas (PANCREAS),Biliary Tract (BILIARY_TRACT),Lymphoid (LYMPH),Liver (LIVER),Bladder/Urinary Tract (BLADDER),Bowel (BOWEL),Thyroid (THYROID),Breast (BREAST),Other (OTHER),VEP_germline
0,,,,,,,,,,,,,,
stop_gained,120.6,106.2,164.0,157.0,83.0,24.0,43.8,24.0,12.0,15.0,14.0,10.0,12.4,41.0
frameshift_variant,123.8,121.6,51.0,42.4,162.2,17.0,8.0,16.0,13.4,9.0,11.0,9.0,5.4,77.0

[[135.30512786 126.1150087  119.02865176 110.39215424 135.74802517
   22.69848708  28.67760075  22.14486544  14.06198956  13.28691927
   13.8405409   10.51881109   9.85446512  65.32735306]
 [109.09487214 101.6849913   95.97134824  89.00784576 109.45197483
   18.30151292  23.12239925  17.85513456  11.33801044  10.71308073
   11.1594591    8.48118891   7.94553488  52.67264694]]

,Lung (LUNG),Esophagus/Stomach (STOMACH),Head and Neck (HEAD_NECK),Skin (SKIN),Pancreas (PANCREAS),Biliary Tract (BILIARY_TRACT),Lymphoid (LYMPH),Liver (LIVER),Bladder/Urinary Tract (BLADDER),Bowel (BOWEL),Thyroid (THYROID),Breast (BREAST),Other (OTHER),VEP_germline
0,,,,,,,,,,,,,,
stop_gained,-2.068977,-2.883201,6.668121,7.13264,-7.411779,0.414612,4.30191,0.59811,-0.83011,0.709139,0.064697,-0.240965,1.220995,-4.69423
frameshift_variant,2.068977,2.883201,-6.668121,-7.13264,7.411779,-0.414612,-4.30191,-0.59811,0.83011,-0.709139,-0.064697,0.240965,-1.220995,4.69423

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/CDKN2A
204
187
181
78
259
55189

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                     count
parent_tissue_code
Breast (BREAST)                         49
Bowel (BOWEL)                           35
Lymphoid (LYMPH)                        31
Liver (LIVER)                           25
Prostate (PROSTATE)                     24
Esophagus/Stomach (STOMACH)             20
Lung (LUNG)                             18
Kidney (KIDNEY)                         12
Bladder/Urinary Tract (BLADDER)         10
CNS/Brain (BRAIN)                        5
Biliary Tract (BILIARY_TRACT)            5
Thyroid (THYROID)                        5
Uterus (UTERUS)                          4
Pancreas (PANCREAS)                      3
Soft Tissue (SOFT_TISSUE)                3
Other (OTHER)                            3
Ampulla of Vater (AMPULLA_OF_VATER)      2
Head and Neck (HEAD_NECK)                2
Ovary/Fallopian Tube (OVARY)             1
Myeloid (MYELOID)                        1
Skin (SKIN)                              1

,Breast (BREAST),Bowel (BOWEL),Lymphoid (LYMPH),Liver (LIVER),VEP_germline
0,,,,,
stop_gained,12.0,10.0,19.2,11.0,32.0
frameshift_variant,30.4,24.0,5.0,10.0,61.0

Breast (BREAST)     42.4
Bowel (BOWEL)       34.0
Lymphoid (LYMPH)    24.2
Liver (LIVER)       21.0
VEP_germline        93.0
dtype: float64
22.257935820058247 0.00017806333142517415 4

,Breast (BREAST),Bowel (BOWEL),Lymphoid (LYMPH),Liver (LIVER),VEP_germline
0,,,,,
stop_gained,12.0,10.0,19.2,11.0,32.0
frameshift_variant,30.4,24.0,5.0,10.0,61.0

[[16.6359739  13.34016775  9.49506058  8.23951538 36.48928239]
 [25.7640261  20.65983225 14.70493942 12.76048462 56.51071761]]

,Breast (BREAST),Bowel (BOWEL),Lymphoid (LYMPH),Liver (LIVER),VEP_germline
0,,,,,
stop_gained,-1.627763,-1.27885,4.289448,1.298891,-1.266539
frameshift_variant,1.627763,1.27885,-4.289448,-1.298891,1.266539

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/CDKN1B
713
704
704

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

180
884
56073

                                 count
parent_tissue_code
Breast (BREAST)                    553
Esophagus/Stomach (STOMACH)        190
Bowel (BOWEL)                       49
Bladder/Urinary Tract (BLADDER)     26
Head and Neck (HEAD_NECK)           10
Uterus (UTERUS)                      9
Liver (LIVER)                        8
Prostate (PROSTATE)                  8
Lung (LUNG)                          8
Skin (SKIN)                          4
CNS/Brain (BRAIN)                    4
Biliary Tract (BILIARY_TRACT)        4
Ovary/Fallopian Tube (OVARY)         3
Lymphoid (LYMPH)                     2
Other (OTHER)                        1
Thymus (THYMUS)                      1
Kidney (KIDNEY)                      1
Myeloid (MYELOID)                    1
Pancreas (PANCREAS)                  1
Thyroid (THYROID)                    1

,Breast (BREAST),Esophagus/Stomach (STOMACH),Bowel (BOWEL),Bladder/Urinary Tract (BLADDER),VEP_germline
0,,,,,
stop_gained,146.8,25.4,7.0,17.0,219.0
frameshift_variant,314.6,40.0,30.0,5.0,436.0

Breast (BREAST)                    461.4
Esophagus/Stomach (STOMACH)         65.4
Bowel (BOWEL)                       37.0
Bladder/Urinary Tract (BLADDER)     22.0
VEP_germline                       655.0
dtype: float64
23.890470366855673 8.40156554155091e-05 4

,Breast (BREAST),Esophagus/Stomach (STOMACH),Bowel (BOWEL),Bladder/Urinary Tract (BLADDER),VEP_germline
0,,,,,
stop_gained,146.8,25.4,7.0,17.0,219.0
frameshift_variant,314.6,40.0,30.0,5.0,436.0

[[154.39497099  21.88433269  12.38104449   7.36170213 219.17794971]
 [307.00502901  43.51566731  24.61895551  14.63829787 435.82205029]]

,Breast (BREAST),Esophagus/Stomach (STOMACH),Bowel (BOWEL),Bladder/Urinary Tract (BLADDER),VEP_germline
0,,,,,
stop_gained,-0.945467,0.946597,-1.90339,4.394019,-0.021446
frameshift_variant,0.945467,-0.946597,1.90339,-4.394019,0.021446

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/CDH1
51
49
49
81
130
56203

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
Head and Neck (HEAD_NECK)           59
Bowel (BOWEL)                       17
Lung (LUNG)                         16
Esophagus/Stomach (STOMACH)          9
Skin (SKIN)                          8
Pancreas (PANCREAS)                  4
Kidney (KIDNEY)                      4
CNS/Brain (BRAIN)                    2
Uterus (UTERUS)                      2
Bladder/Urinary Tract (BLADDER)      2
Adrenal Gland (ADRENAL_GLAND)        1
Liver (LIVER)                        1
Thymus (THYMUS)                      1
Ovary/Fallopian Tube (OVARY)         1
Breast (BREAST)                      1
Thyroid (THYROID)                    1
Soft Tissue (SOFT_TISSUE)            1

                    Head and Neck (HEAD_NECK)  VEP_germline
0
stop_gained                              21.8          55.0
frameshift_variant                       25.2          58.0

Head and Neck (HEAD_NECK)     47.0
VEP_germline                 113.0
dtype: float64
0.008159166509759624 0.9280264870648672 1

                    Head and Neck (HEAD_NECK)  VEP_germline
0
stop_gained                              21.8          55.0
frameshift_variant                       25.2          58.0

[[22.56 54.24]
 [24.44 58.76]]

                    Head and Neck (HEAD_NECK)  VEP_germline
0
stop_gained                         -0.264036      0.264036
frameshift_variant                   0.264036     -0.264036

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/CDC73
370
320
309
198
505
56708

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                     count
parent_tissue_code
Bowel (BOWEL)                           91
Ovary/Fallopian Tube (OVARY)            54
Breast (BREAST)                         52
Lung (LUNG)                             51
Esophagus/Stomach (STOMACH)             48
Prostate (PROSTATE)                     43
Head and Neck (HEAD_NECK)               28
Pancreas (PANCREAS)                     27
Bladder/Urinary Tract (BLADDER)         25
Skin (SKIN)                             13
Uterus (UTERUS)                         12
Biliary Tract (BILIARY_TRACT)           11
Liver (LIVER)                           10
Kidney (KIDNEY)                          9
Cervix (CERVIX)                          7
CNS/Brain (BRAIN)                        7
Other (OTHER)                            4
Lymphoid (LYMPH)                         4
Ampulla of Vater (AMPULLA_OF_VATER)      2
Myeloid (MYELOID)                        2
Soft Tissue (SOFT_TISSUE)                1
Eye (EYE)                                1
Vulva/Vagina (VULVA)                     1
Pleura (PLEURA)                          1
Thymus (THYMUS)                          1

,Bowel (BOWEL),Ovary/Fallopian Tube (OVARY),Breast (BREAST),Lung (LUNG),Esophagus/Stomach (STOMACH),Prostate (PROSTATE),Head and Neck (HEAD_NECK),Pancreas (PANCREAS),Bladder/Urinary Tract (BLADDER),VEP_germline
0,,,,,,,,,,
stop_gained,17.8,19.6,16.6,20.0,11.0,9.0,6.0,6.0,15.0,3995.0
frameshift_variant,62.2,29.0,30.4,21.0,26.0,28.0,20.0,16.6,6.0,11095.0

Bowel (BOWEL)                         80.0
Ovary/Fallopian Tube (OVARY)          48.6
Breast (BREAST)                       47.0
Lung (LUNG)                           41.0
Esophagus/Stomach (STOMACH)           37.0
Prostate (PROSTATE)                   37.0
Head and Neck (HEAD_NECK)             26.0
Pancreas (PANCREAS)                   22.6
Bladder/Urinary Tract (BLADDER)       21.0
VEP_germline                       15090.0
dtype: float64
39.762677924986484 8.38884197328185e-06 9

,Bowel (BOWEL),Ovary/Fallopian Tube (OVARY),Breast (BREAST),Lung (LUNG),Esophagus/Stomach (STOMACH),Prostate (PROSTATE),Head and Neck (HEAD_NECK),Pancreas (PANCREAS),Bladder/Urinary Tract (BLADDER),VEP_germline
0,,,,,,,,,,
stop_gained,17.8,19.6,16.6,20.0,11.0,9.0,6.0,6.0,15.0,3995.0
frameshift_variant,62.2,29.0,30.4,21.0,26.0,28.0,20.0,16.6,6.0,11095.0

[[2.13123455e+01 1.29472499e+01 1.25210030e+01 1.09225771e+01
  9.85695978e+00 9.85695978e+00 6.92651228e+00 6.02073760e+00
  5.59449069e+00 4.02004116e+03]
 [5.86876545e+01 3.56527501e+01 3.44789970e+01 3.00774229e+01
  2.71430402e+01 2.71430402e+01 1.90734877e+01 1.65792624e+01
  1.54055093e+01 1.10699588e+04]]

,Bowel (BOWEL),Ovary/Fallopian Tube (OVARY),Breast (BREAST),Lung (LUNG),Esophagus/Stomach (STOMACH),Prostate (PROSTATE),Head and Neck (HEAD_NECK),Pancreas (PANCREAS),Bladder/Urinary Tract (BLADDER),VEP_germline
0,,,,,,,,,,
stop_gained,-0.890596,2.162062,1.347929,3.211062,0.425581,-0.319067,-0.411369,-0.009875,4.645891,-3.019994
frameshift_variant,0.890596,-2.162062,-1.347929,-3.211062,-0.425581,0.319067,0.411369,0.009875,-4.645891,3.019994

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/BRCA2
178
165
164
115
277
56985

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                     count
parent_tissue_code
Ovary/Fallopian Tube (OVARY)            84
Breast (BREAST)                         49
Lung (LUNG)                             28
Bowel (BOWEL)                           24
Esophagus/Stomach (STOMACH)             22
Bladder/Urinary Tract (BLADDER)         12
Skin (SKIN)                             11
Head and Neck (HEAD_NECK)                9
Prostate (PROSTATE)                      5
Biliary Tract (BILIARY_TRACT)            5
Liver (LIVER)                            5
Cervix (CERVIX)                          4
Kidney (KIDNEY)                          4
Pancreas (PANCREAS)                      3
Thyroid (THYROID)                        3
Lymphoid (LYMPH)                         2
Soft Tissue (SOFT_TISSUE)                2
Uterus (UTERUS)                          2
Ampulla of Vater (AMPULLA_OF_VATER)      1
Other (OTHER)                            1
CNS/Brain (BRAIN)                        1

,Ovary/Fallopian Tube (OVARY),Breast (BREAST),Lung (LUNG),VEP_germline
0,,,,
stop_gained,23.0,12.0,12.0,3031.0
frameshift_variant,47.4,24.0,8.0,7822.0

Ovary/Fallopian Tube (OVARY)       70.4
Breast (BREAST)                    36.0
Lung (LUNG)                        20.0
VEP_germline                    10853.0
dtype: float64
11.441510547609083 0.009563039864355773 3

,Ovary/Fallopian Tube (OVARY),Breast (BREAST),Lung (LUNG),VEP_germline
0,,,,
stop_gained,23.0,12.0,12.0,3031.0
frameshift_variant,47.4,24.0,8.0,7822.0

[[1.97361604e+01 1.00923548e+01 5.60686376e+00 3.04256462e+03]
 [5.06638396e+01 2.59076452e+01 1.43931362e+01 7.81043538e+03]]

,Ovary/Fallopian Tube (OVARY),Breast (BREAST),Lung (LUNG),VEP_germline
0,,,,
stop_gained,0.868824,0.709009,3.18557,-2.303374
frameshift_variant,-0.868824,-0.709009,-3.18557,2.303374

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/BRCA1
45
42
42
17
59
57044

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
Bowel (BOWEL)                       25
Esophagus/Stomach (STOMACH)          8
Lung (LUNG)                          7
Kidney (KIDNEY)                      4
Pancreas (PANCREAS)                  3
Skin (SKIN)                          3
Bladder/Urinary Tract (BLADDER)      2
Breast (BREAST)                      2
CNS/Brain (BRAIN)                    1
Prostate (PROSTATE)                  1
Cervix (CERVIX)                      1
Uterus (UTERUS)                      1
Thyroid (THYROID)                    1

                    Bowel (BOWEL)  VEP_germline
0
stop_gained                   8.4          96.0
frameshift_variant           10.0         134.0

Bowel (BOWEL)     18.4
VEP_germline     230.0
dtype: float64
0.006691810344827573 0.9348029838283887 1

                    Bowel (BOWEL)  VEP_germline
0
stop_gained                   8.4          96.0
frameshift_variant           10.0         134.0

[[  7.73333333  96.66666667]
 [ 10.66666667 133.33333333]]

                    Bowel (BOWEL)  VEP_germline
0
stop_gained              0.327214     -0.327214
frameshift_variant      -0.327214      0.327214

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/BMPR1A
59
51
50
15
64

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

57108

                                 count
parent_tissue_code
Bowel (BOWEL)                       22
Lung (LUNG)                         10
Esophagus/Stomach (STOMACH)          8
Bladder/Urinary Tract (BLADDER)      6
Breast (BREAST)                      4
Liver (LIVER)                        3
Biliary Tract (BILIARY_TRACT)        2
Pancreas (PANCREAS)                  2
Kidney (KIDNEY)                      1
Ovary/Fallopian Tube (OVARY)         1
CNS/Brain (BRAIN)                    1
Lymphoid (LYMPH)                     1
Uterus (UTERUS)                      1
Cervix (CERVIX)                      1
Prostate (PROSTATE)                  1

Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/BARD1
574
456
453
400
852
57960

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
Kidney (KIDNEY)                    258
Pleura (PLEURA)                    176
Eye (EYE)                          131
Esophagus/Stomach (STOMACH)         51
Liver (LIVER)                       49
Lung (LUNG)                         38
Head and Neck (HEAD_NECK)           19
Breast (BREAST)                     18
Skin (SKIN)                         16
Bladder/Urinary Tract (BLADDER)     14
Pancreas (PANCREAS)                 13
Bowel (BOWEL)                       13
Biliary Tract (BILIARY_TRACT)       11
Cervix (CERVIX)                      8
Thymus (THYMUS)                      8
Other (OTHER)                        6
Peritoneum (PERITONEUM)              6
Ovary/Fallopian Tube (OVARY)         4
Prostate (PROSTATE)                  3
Lymphoid (LYMPH)                     3
Uterus (UTERUS)                      3
Penis (PENIS)                        1
Bone (BONE)                          1
Vulva/Vagina (VULVA)                 1
CNS/Brain (BRAIN)                    1

,Kidney (KIDNEY),Pleura (PLEURA),Eye (EYE),Esophagus/Stomach (STOMACH),Liver (LIVER),Lung (LUNG),VEP_germline
0,,,,,,,
stop_gained,49.8,40.8,33.8,18.0,13.0,18.0,88.0
frameshift_variant,149.2,80.2,62.6,22.0,23.0,15.0,207.0

Kidney (KIDNEY)                199.0
Pleura (PLEURA)                121.0
Eye (EYE)                       96.4
Esophagus/Stomach (STOMACH)     40.0
Liver (LIVER)                   36.0
Lung (LUNG)                     33.0
VEP_germline                   295.0
dtype: float64
16.7928856816012 0.010075330397817377 6

,Kidney (KIDNEY),Pleura (PLEURA),Eye (EYE),Esophagus/Stomach (STOMACH),Liver (LIVER),Lung (LUNG),VEP_germline
0,,,,,,,
stop_gained,49.8,40.8,33.8,18.0,13.0,18.0,88.0
frameshift_variant,149.2,80.2,62.6,22.0,23.0,15.0,207.0

[[ 63.40638713  38.55363237  30.71545588  12.74500244  11.47050219
   10.51462701  93.99439298]
 [135.59361287  82.44636763  65.68454412  27.25499756  24.52949781
   22.48537299 201.00560702]]

,Kidney (KIDNEY),Pleura (PLEURA),Eye (EYE),Esophagus/Stomach (STOMACH),Liver (LIVER),Lung (LUNG),VEP_germline
0,,,,,,,
stop_gained,-2.37854,0.474685,0.717733,1.828368,0.559511,2.854556,-0.935985
frameshift_variant,2.37854,-0.474685,-0.717733,-1.828368,-0.559511,-2.854556,0.935985

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/BAP1
151
132
131
104
235
58195

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                 count
parent_tissue_code
Bowel (BOWEL)                      162
Esophagus/Stomach (STOMACH)         26
Liver (LIVER)                       14
Lung (LUNG)                          9
Pancreas (PANCREAS)                  5
Breast (BREAST)                      3
Ovary/Fallopian Tube (OVARY)         3
Biliary Tract (BILIARY_TRACT)        3
Prostate (PROSTATE)                  3
Skin (SKIN)                          3
Uterus (UTERUS)                      1
Bladder/Urinary Tract (BLADDER)      1
CNS/Brain (BRAIN)                    1
Thyroid (THYROID)                    1

                    Bowel (BOWEL)  Esophagus/Stomach (STOMACH)  VEP_germline
0
stop_gained                  14.6                          1.0          49.0
frameshift_variant          129.0                         25.0          90.0

Bowel (BOWEL)                  143.6
Esophagus/Stomach (STOMACH)     26.0
VEP_germline                   139.0
dtype: float64
31.860856738758 1.2064320464001164e-07 2

                    Bowel (BOWEL)  Esophagus/Stomach (STOMACH)  VEP_germline
0
stop_gained                  14.6                          1.0          49.0
frameshift_variant          129.0                         25.0          90.0

[[ 30.06014258   5.4426442   29.09721322]
 [113.53985742  20.5573558  109.90278678]]

                    Bowel (BOWEL)  Esophagus/Stomach (STOMACH)  VEP_germline
0
stop_gained             -4.336876                    -2.237956       5.59727
frameshift_variant       4.336876                     2.237956      -5.59727

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/AXIN2
808
717
712
443
1153
59348

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                     count
parent_tissue_code
Bowel (BOWEL)                          266
Lymphoid (LYMPH)                       234
Lung (LUNG)                            147
Esophagus/Stomach (STOMACH)             80
Kidney (KIDNEY)                         56
Pancreas (PANCREAS)                     43
Prostate (PROSTATE)                     42
Bladder/Urinary Tract (BLADDER)         40
Skin (SKIN)                             40
Liver (LIVER)                           36
Breast (BREAST)                         31
Biliary Tract (BILIARY_TRACT)           22
Uterus (UTERUS)                         21
Thyroid (THYROID)                       18
Ovary/Fallopian Tube (OVARY)            16
CNS/Brain (BRAIN)                       14
Myeloid (MYELOID)                       11
Ampulla of Vater (AMPULLA_OF_VATER)      8
Head and Neck (HEAD_NECK)                7
Soft Tissue (SOFT_TISSUE)                6
Adrenal Gland (ADRENAL_GLAND)            5
Other (OTHER)                            4
Thymus (THYMUS)                          3
Cervix (CERVIX)                          3

,Bowel (BOWEL),Lymphoid (LYMPH),Lung (LUNG),Esophagus/Stomach (STOMACH),Kidney (KIDNEY),Pancreas (PANCREAS),Prostate (PROSTATE),Bladder/Urinary Tract (BLADDER),Skin (SKIN),Liver (LIVER),Breast (BREAST),VEP_germline
0,,,,,,,,,,,,
stop_gained,90.2,66.0,60.0,27.0,18.2,10.8,12.6,17.8,17.2,14.0,13.0,1453.0
frameshift_variant,63.4,87.0,36.6,32.8,25.8,15.2,14.6,6.4,5.8,9.6,12.0,2685.0

Bowel (BOWEL)                       153.6
Lymphoid (LYMPH)                    153.0
Lung (LUNG)                          96.6
Esophagus/Stomach (STOMACH)          59.8
Kidney (KIDNEY)                      44.0
Pancreas (PANCREAS)                  26.0
Prostate (PROSTATE)                  27.2
Bladder/Urinary Tract (BLADDER)      24.2
Skin (SKIN)                          23.0
Liver (LIVER)                        23.6
Breast (BREAST)                      25.0
VEP_germline                       4138.0
dtype: float64
103.52355905889647 3.57266452607474e-17 11

,Bowel (BOWEL),Lymphoid (LYMPH),Lung (LUNG),Esophagus/Stomach (STOMACH),Kidney (KIDNEY),Pancreas (PANCREAS),Prostate (PROSTATE),Bladder/Urinary Tract (BLADDER),Skin (SKIN),Liver (LIVER),Breast (BREAST),VEP_germline
0,,,,,,,,,,,,
stop_gained,90.2,66.0,60.0,27.0,18.2,10.8,12.6,17.8,17.2,14.0,13.0,1453.0
frameshift_variant,63.4,87.0,36.6,32.8,25.8,15.2,14.6,6.4,5.8,9.6,12.0,2685.0

[[  57.6656821    57.44042553   36.26630788   22.45057155   16.51881519
     9.76111806   10.21163121    9.08534835    8.63483521    8.86009178
     9.38569045 1553.51948269]
 [  95.9343179    95.55957447   60.33369212   37.34942845   27.48118481
    16.23888194   16.98836879   15.11465165   14.36516479   14.73990822
    15.61430955 2584.48051731]]

,Bowel (BOWEL),Lymphoid (LYMPH),Lung (LUNG),Esophagus/Stomach (STOMACH),Kidney (KIDNEY),Pancreas (PANCREAS),Prostate (PROSTATE),Bladder/Urinary Tract (BLADDER),Skin (SKIN),Liver (LIVER),Breast (BREAST),VEP_germline
0,,,,,,,,,,,,
stop_gained,5.510143,1.45243,5.037818,1.222581,0.52582,0.421896,0.948414,3.667641,3.697104,2.190365,1.496705,-8.723637
frameshift_variant,-5.510143,-1.45243,-5.037818,-1.222581,-0.52582,-0.421896,-0.948414,-3.667641,-3.697104,-2.190365,-1.496705,8.723637

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/ATM
4060
3978
3963
4977
8940
68288

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_2197/2812644074.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                                     count
parent_tissue_code
Bowel (BOWEL)                         8119
Esophagus/Stomach (STOMACH)            199
Lung (LUNG)                            184
Prostate (PROSTATE)                     80
Liver (LIVER)                           50
Ampulla of Vater (AMPULLA_OF_VATER)     44
Biliary Tract (BILIARY_TRACT)           43
Skin (SKIN)                             38
Thyroid (THYROID)                       31
Pancreas (PANCREAS)                     29
Head and Neck (HEAD_NECK)               21
Breast (BREAST)                         15
Other (OTHER)                           15
Adrenal Gland (ADRENAL_GLAND)           13
Bladder/Urinary Tract (BLADDER)         12
Uterus (UTERUS)                         12
Ovary/Fallopian Tube (OVARY)            10
CNS/Brain (BRAIN)                        7
Kidney (KIDNEY)                          5
Soft Tissue (SOFT_TISSUE)                3
Lymphoid (LYMPH)                         3
Cervix (CERVIX)                          2
Bone (BONE)                              2
Myeloid (MYELOID)                        1
Pleura (PLEURA)                          1
Thymus (THYMUS)                          1

,Bowel (BOWEL),Esophagus/Stomach (STOMACH),Lung (LUNG),Prostate (PROSTATE),Liver (LIVER),Ampulla of Vater (AMPULLA_OF_VATER),Biliary Tract (BILIARY_TRACT),Skin (SKIN),Thyroid (THYROID),Pancreas (PANCREAS),VEP_germline
0,,,,,,,,,,,
stop_gained,3421.8,88.0,83.4,29.4,16.2,14.8,20.2,27.4,7.8,10.6,866.0
frameshift_variant,2441.2,94.0,81.6,44.6,26.8,19.2,19.8,6.6,13.2,14.4,1507.0

Bowel (BOWEL)                          5863.0
Esophagus/Stomach (STOMACH)             182.0
Lung (LUNG)                             165.0
Prostate (PROSTATE)                      74.0
Liver (LIVER)                            43.0
Ampulla of Vater (AMPULLA_OF_VATER)      34.0
Biliary Tract (BILIARY_TRACT)            40.0
Skin (SKIN)                              34.0
Thyroid (THYROID)                        21.0
Pancreas (PANCREAS)                      25.0
VEP_germline                           2373.0
dtype: float64
347.45487889474697 1.3818181739041462e-68 10

,Bowel (BOWEL),Esophagus/Stomach (STOMACH),Lung (LUNG),Prostate (PROSTATE),Liver (LIVER),Ampulla of Vater (AMPULLA_OF_VATER),Biliary Tract (BILIARY_TRACT),Skin (SKIN),Thyroid (THYROID),Pancreas (PANCREAS),VEP_germline
0,,,,,,,,,,,
stop_gained,3421.8,88.0,83.4,29.4,16.2,14.8,20.2,27.4,7.8,10.6,866.0
frameshift_variant,2441.2,94.0,81.6,44.6,26.8,19.2,19.8,6.6,13.2,14.4,1507.0

[[3036.52279196   94.26013101   85.45561328   38.32554778   22.27025073
    17.60903546   20.71651231   17.60903546   10.87616896   12.94782019
  1229.00709284]
 [2826.47720804   87.73986899   79.54438672   35.67445222   20.72974927
    16.39096454   19.28348769   16.39096454   10.12383104   12.05217981
  1143.99290716]]

,Bowel (BOWEL),Esophagus/Stomach (STOMACH),Lung (LUNG),Prostate (PROSTATE),Liver (LIVER),Ampulla of Vater (AMPULLA_OF_VATER),Biliary Tract (BILIARY_TRACT),Skin (SKIN),Thyroid (THYROID),Pancreas (PANCREAS),VEP_germline
0,,,,,,,,,,,
stop_gained,17.325421,-0.938354,-0.323291,-2.085213,-1.857113,-0.965967,-0.163811,3.366901,-1.345009,-0.941061,-17.431063
frameshift_variant,-17.325421,0.938354,0.323291,2.085213,1.857113,0.965967,0.163811,-3.366901,1.345009,0.941061,17.431063

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/APC
Wed Mar 12 16:48:44 2025

## Comparing somatic combined with germline

In [593]:
## now run stats for all genes combining all somatic tissue types (gl vs s for frameshift vs stop-gain):

start_time_block2=time.asctime(time.localtime())
print(start_time_block2)

somaticconcat_allTSG=pd.DataFrame()
alloutputdf=pd.DataFrame()

#3-all TSG, excluding splice region, all output stats to this df gene-wise
allTSG_df_nospliceregion=pd.DataFrame()

FLAG1_count=FLAG5_count=FLAGFISHER_count=0

cosmicconcat_OT_parent_annotated_readcsv=pd.read_csv("/Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/COSMIC/Cosmic_MutantCensus_Tsv_v98_GRCh38/cosmicconcat_41TSGs_NCITtoOT_dropna_parentOT_11-25-24.txt", sep="\t")
        
parentpath="/Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023"
os.chdir(parentpath)
# loading VEP consequence titles (category names) to use as index to join cbio and clinvar processed dfs:
VEP_calc_consequences=pd.read_csv("VEP_calculated_consequences_8-26-24.txt", sep="\t", header=None) #edited to add 'splice_site_variant' on 8-26-24


#read file with folder names and MANE Select transcript identifiers (or MANE Plus Clinical in the case of SMARCA4)
TranscriptID= pd.read_csv("TSGfolder_MANESelect_names_aalength_GeneIDs_6-13-24.txt", sep="\t")

Hypermutators=pd.read_csv("cbio_sampleinfo_tmb_gt10_12-14-23.txt", sep="\t")

for index, row in TranscriptID.iterrows():
    
    # Loop through each folder name
    folder_name=TranscriptID.loc[index]["Gene Symbol"]
    #if folder name exists, list all files in that folder then change directory to that folder
    if os.path.exists(folder_name) and os.path.isdir(folder_name):# and (folder_name == "RB1"):
        filelist=os.listdir(folder_name)
        os.chdir(folder_name)
        
        
        clinvar_cbio_tocompare=pd.read_csv("Python_coderun_6-13-24_clinvar_extract_and_process_again/Python_clinvar_cbio_tocompare_8-16-24.txt", sep="\t")
        Variation_interpretation_toexclude = ["Pathogenic", "Likely pathogenic", "Pathogenic/Likely pathogenic", "Conflicting interpretations of pathogenicity greater than or equal to 75"]
        clinvar_cbio_tocompare_VUSLBB=clinvar_cbio_tocompare[~clinvar_cbio_tocompare["GL_first_Description"].isin(Variation_interpretation_toexclude)]
        #print("shared count")
        #print(len(clinvar_cbio_tocompare))
        #print("shared that are VUSLBB")
        #print(len(clinvar_cbio_tocompare_VUSLBB))
        cbio_VEP=pd.read_csv("Python_coderun_7-11-24_cbio_process_again/Python_cbio_processed_VEP_MANE_CAID_OTtissue_10-24-24.txt", sep="\t")
        #print("cbio VEP len")
        cbioCount1=len(cbio_VEP)
        #print(len(cbio_VEP))
        VEP_categories_tofilter_list=["synonymous_variant","5_prime_UTR_variant", "3_prime_UTR_variant", "non_coding_transcript_exon_variant", "intron_variant", "non_coding_transcript_variant", "upstream_gene_variant", "downstream_gene_variant", "regulatory_region_ablation", "regulatory_region_amplification", "regulatory_region_variant", "intergenic_variant", "splice_region_variant"] #8-23-24 #, ">=50bp_indel"]
        cbio_VEP=cbio_VEP[~cbio_VEP["collapsed_Consequence"].isin(VEP_categories_tofilter_list)]
        #print("cbio VEP len after filter VEP categories")
        #print(len(cbio_VEP))
        cbioCount2=len(cbio_VEP)
        Hypermutators_to_filter=Hypermutators.set_index('uniqueSampleKey').index
        #print("with hypermutators count QC same as above")
        totalbeforehypermutatorfilter=len(cbio_VEP)
        #print(len(cbio_VEP))
        cbio_VEP_nohypermutator=cbio_VEP[~cbio_VEP["uniqueSampleKey"].isin(Hypermutators_to_filter)]
        cbio_VEP=cbio_VEP_nohypermutator
        #print("without hypermutators count")
        #print(len(cbio_VEP))
        #print("% vars lost to hypermutator filter=#total-#afterfilter/#total")
        #print(((totalbeforehypermutatorfilter-len(cbio_VEP))*100)/totalbeforehypermutatorfilter)
        removetheseVUSLBB=clinvar_cbio_tocompare_VUSLBB["@id"]
        cbio_VEP_noVUSLBB=cbio_VEP[~cbio_VEP["@id"].isin(removetheseVUSLBB)]
        #print("without VUSLBB")
        #print(len(cbio_VEP_noVUSLBB))
        #print("# variants lost after VUSLBB filter")
        #print(len(cbio_VEP)-len(cbio_VEP_noVUSLBB))
        #print("% vars lost to VUSLBB filter=#total-#afterfilter/#total")
        #print(((len(cbio_VEP)-len(cbio_VEP_noVUSLBB))*100)/len(cbio_VEP))
        cbio_VEP_cancertypeall=cbio_VEP_noVUSLBB
        print(len(cbio_VEP_cancertypeall))
        #cbio=pd.concat([cbio, cbio_VEP_cancertype])
        cbio_VEP_cancertype_uniqueOT=cbio_VEP_cancertypeall[cbio_VEP_cancertypeall["unique_count_parents_in_OncoTree"]==1]
        print(len(cbio_VEP_cancertype_uniqueOT))
        
        cbio_VEP_cancertype_uniqueOT_0tummorAltCount=cbio_VEP_cancertype_uniqueOT[cbio_VEP_cancertype_uniqueOT["tumorAltCount"]==0]
        cbio_VEP_cancertype_uniqueOT_no0tummorAltCount=cbio_VEP_cancertype_uniqueOT.drop(cbio_VEP_cancertype_uniqueOT_0tummorAltCount.index)
        print(len(cbio_VEP_cancertype_uniqueOT_no0tummorAltCount))
        
        folder_name_aslist=[folder_name]
        cosmicconcat_OT_parent_annotated_readcsv_renamecolumns=cosmicconcat_OT_parent_annotated_readcsv.rename(columns={"unique_count_parents_in_OncoTree":'empty1', 'parent_tissue_code_list': 'empty2', "count_parents_in_OncoTree":"empty3", "parent_tissue_code":"empty4", '1': "unique_count_parents_in_OncoTree", '2': "parent_tissue_code_list", '3': "count_parents_in_OncoTree", '4':"parent_tissue_code"})

        cosmic=cosmicconcat_OT_parent_annotated_readcsv_renamecolumns[cosmicconcat_OT_parent_annotated_readcsv_renamecolumns["GENE_SYMBOL"].isin(folder_name_aslist)==True]
        print(len(cosmic))
        cosmic_uniqueOT=cosmic[cosmic["unique_count_parents_in_OncoTree"]==1]
        
        somaticconcat=pd.concat([cbio_VEP_cancertype_uniqueOT_no0tummorAltCount,cosmic_uniqueOT])
        print(len(somaticconcat))
        
        
        somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")
        somaticconcat=somaticconcat.rename(columns={"level_0":"level_0_hgvsg"})
        somaticconcat=somaticconcat.reset_index()
        
        somaticconcat_allTSG=pd.concat([somaticconcat_allTSG,somaticconcat])
        print(len(somaticconcat_allTSG))
        
        #dfparentOT=pd.DataFrame(somaticconcat["parent_tissue_code"].value_counts())
        #dfparentOT_filtergte25=dfparentOT[dfparentOT["count"]>=25]
        #dfparentOT_filtergte25_resetindex=dfparentOT_filtergte25.reset_index()
        #display(dfparentOT)
        #adjpfactor=len(dfparentOT_filtergte25_resetindex)
        #if (adjpfactor!=0):
        #    df_forstats=VEP_calc_consequences.set_index(0)
        #    
        #    for index, row in dfparentOT_filtergte25_resetindex.iterrows():
        #       OTparent=dfparentOT_filtergte25_resetindex.loc[index]["parent_tissue_code"]
        #        somaticconcat_singleOTparent=somaticconcat[somaticconcat["parent_tissue_code"].str.contains(OTparent.split("(")[0])==True]
        #       #print(len(somaticconcat_singleOTparent), OTparent)
        #        
        #initialize default dict to select 1 variant at random from list of variants per patient (for patients with multiple variants in the same gene):
        cbio_VEP_dict=defaultdict(list)
            
            
        # loading VEP consequence titles (categories) to use as index to join randomavg dfs:
        cbio_VEP_calc_consequences=VEP_calc_consequences
        cbio_VEP_randomavg_means=cbio_VEP_calc_consequences.set_index(0)
        #making dictionary of list of variants per patient id in the form ({patient1: [var1consequence, var2consequence, var3consequence,...], patient2:[var1consequence,var2consequence,..]})
        #cbio_VEP_cancertype=somaticconcat_singleOTparent
        cbio_VEP_cancertype=somaticconcat
        for index, row in cbio_VEP_cancertype.iterrows():
            patientid=cbio_VEP_cancertype.loc[index]["patientid"]
            VEPresult=cbio_VEP_cancertype.loc[index]["collapsed_Consequence"]
            cbio_VEP_dict[patientid].append(VEPresult)

        #print(len(cbio_VEP_dict))
        #randomly selecting 1 variant per patient id and summarizing distribution, repeating 5 times
        for i in range(5):
            cbio_VEP_random = {k:random.choice(v) for k,v in list(cbio_VEP_dict.items())}
            list_VEP_random=[]
            for key, val in cbio_VEP_random.items():
                eachrow=[key,val]
                list_VEP_random.append(eachrow)
            #convert list to df of 1 variant per patient [patient1:var2consequence, patient2:var1consequence, ...]
            dfconvert= pd.DataFrame(list_VEP_random)
            #summarize counts per VEP category and convert to df having VEP category as index
            cbio_VEP_randomavg=pd.DataFrame(dfconvert[1].value_counts())
            #above is a df of current random selection having row header=VEP category and only 1 column of the counts per category (aka row) derived from current random selection
            #rename counts column in above df with the loop number (1/2/3/4/5) + join together with previous df (if not the 1st random selection of 5) and calc mean of all 5 sets of distributions
            rename=f"VEP_count_{i}"
            cbio_VEP_randomavg_rename=cbio_VEP_randomavg.rename(columns={"count":rename})
            cbio_VEP_randomavg_means=cbio_VEP_randomavg_means.join(cbio_VEP_randomavg_rename)
        #replace all missing values with 0 to calc mean
        cbio_VEP_randomavg_means_fill0=cbio_VEP_randomavg_means.fillna(0)
        #calc mean
        cbio_VEP_randomavg_means_fill0['mean']=cbio_VEP_randomavg_means_fill0.mean(axis=1)


        ## added 3-12-25:
        #dfparentOT_filtergte25_resetindex.groupby(by=["parent_tissue_code","collapsed_Consequence"]).size()

        OTparent="somatic"
        #rename somatic column in cbio df
        cbio_VEP_randomavg_means_fill0_rename=cbio_VEP_randomavg_means_fill0.rename(columns={"mean":f"{OTparent}"})
                
        cbio_VEP_randomavg_means_fill0_rename=cbio_VEP_randomavg_means_fill0_rename.filter(items=[f"{OTparent}"])
                
                
        #combine gl and s dfs
        #df_forstats = df_forstats.join(cbio_VEP_randomavg_means_fill0_rename)
                
        clinvar_VEP_cancertype=pd.read_csv("Python_coderun_6-13-24_clinvar_extract_and_process_again/Python_clinvar_processed_VEP_MANE_8-15-24.txt", sep="\t")
         
        clinvar_VEP_MANE=VEP_calc_consequences.set_index(0)
        #create list with each VEP category in data, plus occurrence list of number of times each variant seen in that category
        clinvar_VEPresult=defaultdict(list)
        for index, row in clinvar_VEP_cancertype.iterrows():
            VEPresult=clinvar_VEP_cancertype.loc[index]["collapsed_Consequence"]
            variantcount=clinvar_VEP_cancertype.loc[index]["Occurrence"]
            clinvar_VEPresult[VEPresult].append(variantcount)
        #sum the list of occurrence per VEP category
        clinvar_VEPresult_sumoccurrence = {k: sum(v) for (k, v) in clinvar_VEPresult.items()}
        #create dataframe from dictionary
        clinvar_dfconvert=pd.DataFrame.from_dict(clinvar_VEPresult_sumoccurrence, orient='index')
        #join with VEP consequence df
        clinvar_VEP=clinvar_VEP_MANE.join(clinvar_dfconvert)
        #replace missing values with 0
        clinvar_VEP_fill0=clinvar_VEP.fillna(0)
        #rename germline column
        clinvar_VEP_fill0_rename=clinvar_VEP_fill0.rename(columns={0:"VEP_germline"})
                
        df_gl_s = cbio_VEP_randomavg_means_fill0_rename.join(clinvar_VEP_fill0_rename)
                
        #filter out categories filtered by cbio (excep for TERT- diff set since cbio includes promoter variants)
        if folder_name=="TERT":
            VEP_categories_tofilter_list=["synonymous_variant", "3_prime_UTR_variant", "intron_variant", "downstream_gene_variant"]
        else:    
            VEP_categories_tofilter_list=["synonymous_variant","5_prime_UTR_variant", "3_prime_UTR_variant", "non_coding_transcript_exon_variant", "intron_variant", "non_coding_transcript_variant", "upstream_gene_variant", "downstream_gene_variant", "regulatory_region_ablation", "regulatory_region_amplification", "regulatory_region_variant", "intergenic_variant", "splice_region_variant", "splice_donor_variant","splice_acceptor_variant", "missense_variant", "inframe_deletion", ">=50bp_indel", "inframe_insertion", "protein_altering_variant", "start_lost", "stop_lost"]

        df_gl_s_filter=df_gl_s.drop(VEP_categories_tofilter_list)
        #display(df_gl_s_filter)
        #df_gl_s_allgte5=df_gl_s_filter[(df_gl_s_filter.ne(0)).any(axis=1)]
        df_gl_s_allgte5=df_gl_s_filter[~(df_gl_s_filter < 5).all(axis=1)]
        display(df_gl_s_allgte5)
        print(df_gl_s_allgte5.sum())
        #run chi-square test from scipy
        from scipy.stats import chi2_contingency
        c_nospliceregion, p_nospliceregion, dof_nospliceregion, expected_nospliceregion = chi2_contingency(df_gl_s_allgte5)
        print(c_nospliceregion, p_nospliceregion, dof_nospliceregion) 
        display(df_gl_s_allgte5)
        print(expected_nospliceregion)

        expected_df=pd.DataFrame(expected_nospliceregion)
        count_less_than_5 = (expected_df < 5).sum().sum()
        if count_less_than_5/expected_df.size > 0.25:
            FLAG5=1
        else:
            FLAG5=0

        import numpy as np    
        import statsmodels.api as sm   
        table_nospliceregion = sm.stats.Table(df_gl_s_allgte5)   # Standardized residuals

               
        #Pearson_residuals to output
        Pearson_residuals_standardized_nospliceregion = table_nospliceregion.standardized_resids
        display(Pearson_residuals_standardized_nospliceregion)
        print(f"FLAG5 = {FLAG5}")

        outputdf=pd.DataFrame({"Gene":[folder_name],"p-value":[p_nospliceregion], "adjp":[p_nospliceregion*40],"somatic_ASPR":[Pearson_residuals_standardized_nospliceregion.loc["stop_gained"]["somatic"]], "germline_ASPR":[Pearson_residuals_standardized_nospliceregion.loc["stop_gained"]["VEP_germline"]]})
        alloutputdf=pd.concat([alloutputdf,outputdf])

        print("Current directory:", os.getcwd())
        os.chdir(parentpath)
    else:
        print(f"Folder '{folder_name}' not found.")

end_time_block2=time.asctime(time.localtime())
print(end_time_block2)

Thu Jun 19 14:32:45 2025

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:16: DtypeWarning: Columns (24,177) have mixed types. Specify dtype option on import or set low_memory=False.
  cosmicconcat_OT_parent_annotated_readcsv=pd.read_csv("/Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/COSMIC/Cosmic_MutantCensus_Tsv_v98_GRCh38/cosmicconcat_41TSGs_NCITtoOT_dropna_parentOT_11-25-24.txt", sep="\t")

131
125
125
471
596
596

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained           113.4          32.0
frameshift_variant    362.6          30.0

somatic         476.0
VEP_germline     62.0
dtype: float64
20.09353017141189 7.3745723686308975e-06 1

                    somatic  VEP_germline
0
stop_gained           113.4          32.0
frameshift_variant    362.6          30.0

[[128.64386617  16.75613383]
 [347.35613383  45.24386617]]

                     somatic  VEP_germline
0
stop_gained        -4.634596      4.634596
frameshift_variant  4.634596     -4.634596

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/WT1
634
634
634

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

2258
2877
3473

                    somatic  VEP_germline
0
stop_gained           383.8          84.0
frameshift_variant   1460.0         135.0

somatic         1843.8
VEP_germline     219.0
dtype: float64
33.35295998699267 7.68607460767947e-09 1

                    somatic  VEP_germline
0
stop_gained           383.8          84.0
frameshift_variant   1460.0         135.0

[[ 418.1353694   49.6646306]
 [1425.6646306  169.3353694]]

                     somatic  VEP_germline
0
stop_gained        -5.860545      5.860545
frameshift_variant  5.860545     -5.860545

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/VHL
268
244
244
169
413
3886

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained           132.0         503.0
frameshift_variant    141.8         671.0

somatic          273.8
VEP_germline    1174.0
dtype: float64
2.3823833563883507 0.12271020597209409 1

                    somatic  VEP_germline
0
stop_gained           132.0         503.0
frameshift_variant    141.8         671.0

[[120.0877193 514.9122807]
 [153.7122807 659.0877193]]

                     somatic  VEP_germline
0
stop_gained         1.611122     -1.611122
frameshift_variant -1.611122      1.611122

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/TSC2

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

281
243
242
107
348
4234

                    somatic  VEP_germline
0
stop_gained           130.8         344.0
frameshift_variant    130.6         470.0

somatic         261.4
VEP_germline    814.0
dtype: float64
4.543910243405443 0.03303604456200818 1

                    somatic  VEP_germline
0
stop_gained           130.8         344.0
frameshift_variant    130.6         470.0

[[115.41074949 359.38925051]
 [145.98925051 454.61074949]]

                     somatic  VEP_germline
0
stop_gained         2.203228     -2.203228
frameshift_variant -2.203228      2.203228

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/TSC1

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:46: DtypeWarning: Columns (34,35) have mixed types. Specify dtype option on import or set low_memory=False.
  cbio_VEP=pd.read_csv("Python_coderun_7-11-24_cbio_process_again/Python_cbio_processed_VEP_MANE_CAID_OTtissue_10-24-24.txt", sep="\t")
/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

17785
16662
16627
16599
33153
37387

                    somatic  VEP_germline
0
stop_gained          4455.6         192.0
frameshift_variant   3612.6         462.0

somatic         8068.2
VEP_germline     654.0
dtype: float64
161.5695110761577 5.137350607077052e-37 1

                    somatic  VEP_germline
0
stop_gained          4455.6         192.0
frameshift_variant   3612.6         462.0

[[4299.11791979  348.48208021]
 [3769.08208021  305.51791979]]

                      somatic  VEP_germline
0
stop_gained         12.751745    -12.751745
frameshift_variant -12.751745     12.751745

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/TP53
70
62
62
20
82
37469

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained            17.0          22.0
frameshift_variant     34.0          64.0

somatic         51.0
VEP_germline    86.0
dtype: float64
0.6024221405914775 0.4376553591844814 1

                    somatic  VEP_germline
0
stop_gained            17.0          22.0
frameshift_variant     34.0          64.0

[[14.51824818 24.48175182]
 [36.48175182 61.51824818]]

                     somatic  VEP_germline
0
stop_gained         0.971985     -0.971985
frameshift_variant -0.971985      0.971985

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/SUFU

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

566
521
521
267
787
38256

                    somatic  VEP_germline
0
stop_gained           223.2          90.0
frameshift_variant    273.8         180.0

somatic         497.0
VEP_germline    270.0
dtype: float64
9.230875587159025 0.002379678232686392 1

                    somatic  VEP_germline
0
stop_gained           223.2          90.0
frameshift_variant    273.8         180.0

[[202.94706649 110.25293351]
 [294.05293351 159.74706649]]

                     somatic  VEP_germline
0
stop_gained         3.115142     -3.115142
frameshift_variant -3.115142      3.115142

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/STK11
139
125
125

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

19
144
38400

                    somatic  VEP_germline
0
stop_gained            38.4          19.0
frameshift_variant     55.0          23.0

somatic         93.4
VEP_germline    42.0
dtype: float64
0.06826455279560613 0.7938805517393791 1

                    somatic  VEP_germline
0
stop_gained            38.4          19.0
frameshift_variant     55.0          23.0

[[39.59497784 17.80502216]
 [53.80502216 24.19497784]]

                     somatic  VEP_germline
0
stop_gained        -0.449248      0.449248
frameshift_variant  0.449248     -0.449248

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/SMARCB1
457
395
395
257
650
39050

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained           184.6          87.0
frameshift_variant    144.0          85.0

somatic         328.6
VEP_germline    172.0
dtype: float64
1.2081506807218734 0.27169868434695754 1

                    somatic  VEP_germline
0
stop_gained           184.6          87.0
frameshift_variant    144.0          85.0

[[178.2815821  93.3184179]
 [150.3184179  78.6815821]]

                     somatic  VEP_germline
0
stop_gained         1.193614     -1.193614
frameshift_variant -1.193614      1.193614

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/SMARCA4
1356
1247
1247
541
1788
40838

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained           434.8          78.0
frameshift_variant    312.2         175.0

somatic         747.0
VEP_germline    253.0
dtype: float64
55.602548856908456 8.870853791301046e-14 1

                    somatic  VEP_germline
0
stop_gained           434.8          78.0
frameshift_variant    312.2         175.0

[[383.0616 129.7384]
 [363.9384 123.2616]]

                     somatic  VEP_germline
0
stop_gained         7.529477     -7.529477
frameshift_variant -7.529477      7.529477

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/SMAD4
39
36
36
12
48
40886

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained            16.4         131.0
frameshift_variant     10.6         148.0

somatic          27.0
VEP_germline    279.0
dtype: float64
1.3627870822910937 0.24305503936992748 1

                    somatic  VEP_germline
0
stop_gained            16.4         131.0
frameshift_variant     10.6         148.0

[[ 13.00588235 134.39411765]
 [ 13.99411765 144.60588235]]

                     somatic  VEP_germline
0
stop_gained         1.369067     -1.369067
frameshift_variant -1.369067      1.369067

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/SDHA
1546
1435
1431
773
2152

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

43038

                    somatic  VEP_germline
0
stop_gained           886.2         272.0
frameshift_variant    662.4         432.0

somatic         1548.6
VEP_germline     704.0
dtype: float64
66.211284357418 4.0508678956097113e-16 1

                    somatic  VEP_germline
0
stop_gained           886.2         272.0
frameshift_variant    662.4         432.0

[[796.23036491 361.96963509]
 [752.36963509 342.03036491]]

                     somatic  VEP_germline
0
stop_gained         8.182505     -8.182505
frameshift_variant -8.182505      8.182505

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/RB1
2246
1900
1888
1948
3832

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

46870

                    somatic  VEP_germline
0
stop_gained           764.2         304.0
frameshift_variant   1184.4         556.0

somatic         1948.6
VEP_germline     860.0
dtype: float64
3.627452251628686 0.056833756900302526 1

                    somatic  VEP_germline
0
stop_gained           764.2         304.0
frameshift_variant   1184.4         556.0

[[ 741.11461938  327.08538062]
 [1207.48538062  532.91461938]]

                     somatic  VEP_germline
0
stop_gained         1.946751     -1.946751
frameshift_variant -1.946751      1.946751

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/PTEN
224
196
195
280
475
47345

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained           159.4         174.0
frameshift_variant    224.0         333.0

somatic         383.4
VEP_germline    507.0
dtype: float64
4.601952194245423 0.03193557147185642 1

                    somatic  VEP_germline
0
stop_gained           159.4         174.0
frameshift_variant    224.0         333.0

[[143.5597035 189.8402965]
 [239.8402965 317.1597035]]

                     somatic  VEP_germline
0
stop_gained         2.215137     -2.215137
frameshift_variant -2.215137      2.215137

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/PTCH1
91
83
82
42
123
47468

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained            48.0         761.0
frameshift_variant     64.0        1499.0

somatic          112.0
VEP_germline    2260.0
dtype: float64
3.607202171571626 0.057529827987992645 1

                    somatic  VEP_germline
0
stop_gained            48.0         761.0
frameshift_variant     64.0        1499.0

[[  38.1989882  770.8010118]
 [  73.8010118 1489.1989882]]

                     somatic  VEP_germline
0
stop_gained         2.001363     -2.001363
frameshift_variant -2.001363      2.001363

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/PALB2

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

326
243
243
656
899
48367

                    somatic  VEP_germline
0
stop_gained           315.6         106.0
frameshift_variant    368.6          73.0

somatic         684.2
VEP_germline    179.0
dtype: float64
9.214285671305314 0.002401338890399639 1

                    somatic  VEP_germline
0
stop_gained           315.6         106.0
frameshift_variant    368.6          73.0

[[334.17367933  87.42632067]
 [350.02632067  91.57367933]]

                    somatic  VEP_germline
0
stop_gained        -3.11948       3.11948
frameshift_variant  3.11948      -3.11948

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/NF2
1107
967
967
795
1760
50127

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained           589.8        1585.0
frameshift_variant    570.2        2900.0

somatic         1160.0
VEP_germline    4485.0
dtype: float64
92.89634806230382 5.510609312808125e-22 1

                    somatic  VEP_germline
0
stop_gained           589.8        1585.0
frameshift_variant    570.2        2900.0

[[ 446.90310009 1727.89689991]
 [ 713.09689991 2757.10310009]]

                     somatic  VEP_germline
0
stop_gained         9.672118     -9.672118
frameshift_variant -9.672118      9.672118

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/NF1
143
103
103
212
315
50442

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained            82.8         835.0
frameshift_variant    197.0        2174.0

somatic          279.8
VEP_germline    3009.0
dtype: float64
0.3452256833142602 0.5568282778337744 1

                    somatic  VEP_germline
0
stop_gained            82.8         835.0
frameshift_variant    197.0        2174.0

[[  78.08332523  839.71667477]
 [ 201.71667477 2169.28332523]]

                    somatic  VEP_germline
0
stop_gained         0.65723      -0.65723
frameshift_variant -0.65723       0.65723

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/MSH6
109
63
63
138
201
50643

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained            80.8         757.0
frameshift_variant     68.4        1539.0

somatic          149.2
VEP_germline    2296.0
dtype: float64
26.98328872543259 2.0522208994113835e-07 1

                    somatic  VEP_germline
0
stop_gained            80.8         757.0
frameshift_variant     68.4        1539.0

[[  51.12046458  786.67953542]
 [  98.07953542 1509.32046458]]

                     somatic  VEP_germline
0
stop_gained         5.283554     -5.283554
frameshift_variant -5.283554      5.283554

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/MSH2
99
78
78
133
211
50854

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained            58.0         516.0
frameshift_variant     81.4        1176.0

somatic          139.4
VEP_germline    1692.0
dtype: float64
6.880641858365406 0.008713426655285395 1

                    somatic  VEP_germline
0
stop_gained            58.0         516.0
frameshift_variant     81.4        1176.0

[[  43.69094682  530.30905318]
 [  95.70905318 1161.69094682]]

                     somatic  VEP_germline
0
stop_gained         2.718075     -2.718075
frameshift_variant -2.718075      2.718075

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/MLH1
229
214
213
92
305
51159

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained            85.2         183.0
frameshift_variant    172.8         349.0

somatic         258.0
VEP_germline    532.0
dtype: float64
0.091626221902425 0.7621198424520147 1

                    somatic  VEP_germline
0
stop_gained            85.2         183.0
frameshift_variant    172.8         349.0

[[ 87.58936709 180.61063291]
 [170.41063291 351.38936709]]

                     somatic  VEP_germline
0
stop_gained        -0.382804      0.382804
frameshift_variant  0.382804     -0.382804

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/MEN1

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

51
43
43
33
76
51235

                    somatic  VEP_germline
0
stop_gained            22.6          18.0
frameshift_variant     15.0          18.0

somatic         37.6
VEP_germline    36.0
dtype: float64
0.40583312777003155 0.5240920581567887 1

                    somatic  VEP_germline
0
stop_gained            22.6          18.0
frameshift_variant     15.0          18.0

[[20.74130435 19.85869565]
 [16.85869565 16.14130435]]

                     somatic  VEP_germline
0
stop_gained         0.871485     -0.871485
frameshift_variant -0.871485      0.871485

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/MAX
87
68
68
47
115

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

51350

                    somatic  VEP_germline
0
stop_gained            19.0         156.0
frameshift_variant     77.0         362.0

somatic          96.0
VEP_germline    518.0
dtype: float64
3.7447204902708497 0.052974586704734226 1

                    somatic  VEP_germline
0
stop_gained            19.0         156.0
frameshift_variant     77.0         362.0

[[ 27.36156352 147.63843648]
 [ 68.63843648 370.36156352]]

                     somatic  VEP_germline
0
stop_gained        -2.058203      2.058203
frameshift_variant  2.058203     -2.058203

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/FLCN
26
26
25
12
36

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

51386

                    somatic  VEP_germline
0
stop_gained            15.0         118.0
frameshift_variant     11.0         206.0

somatic          26.0
VEP_germline    324.0
dtype: float64
3.7640757186597598 0.05236479154387908 1

                    somatic  VEP_germline
0
stop_gained            15.0         118.0
frameshift_variant     11.0         206.0

[[  9.88 123.12]
 [ 16.12 200.88]]

                     somatic  VEP_germline
0
stop_gained         2.150093     -2.150093
frameshift_variant -2.150093      2.150093

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/FH
138
109
109
179
288

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

51674

                    somatic  VEP_germline
0
stop_gained            56.6         287.0
frameshift_variant     49.4         505.0

somatic         106.0
VEP_germline    792.0
dtype: float64
10.93712767876244 0.0009425617986278413 1

                    somatic  VEP_germline
0
stop_gained            56.6         287.0
frameshift_variant     49.4         505.0

[[ 40.55857461 303.04142539]
 [ 65.44142539 488.95857461]]

                    somatic  VEP_germline
0
stop_gained         3.41353      -3.41353
frameshift_variant -3.41353       3.41353

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/DICER1
72
61
61

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

68
129
51803

                    somatic  VEP_germline
0
stop_gained            54.0          15.0
frameshift_variant     47.0          19.0

somatic         101.0
VEP_germline     34.0
dtype: float64
0.5547488092799047 0.4563837990149675 1

                    somatic  VEP_germline
0
stop_gained            54.0          15.0
frameshift_variant     47.0          19.0

[[51.62222222 17.37777778]
 [49.37777778 16.62222222]]

                     somatic  VEP_germline
0
stop_gained         0.943138     -0.943138
frameshift_variant -0.943138      0.943138

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/CYLD
84
74
74
56
130

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

51933

                    somatic  VEP_germline
0
stop_gained            40.4         322.0
frameshift_variant     45.2         745.0

somatic           85.6
VEP_germline    1067.0
dtype: float64
9.871931746161149 0.001678192185708469 1

                    somatic  VEP_germline
0
stop_gained            40.4         322.0
frameshift_variant     45.2         745.0

[[ 26.91431546 335.48568454]
 [ 58.68568454 731.51431546]]

                     somatic  VEP_germline
0
stop_gained         3.262941     -3.262941
frameshift_variant -3.262941      3.262941

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/CHEK2

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

66
62
62
822
884
52817

                    somatic  VEP_germline
0
stop_gained            27.8           8.0
frameshift_variant    574.8          20.0

somatic         602.6
VEP_germline     28.0
dtype: float64
24.381190721348748 7.903662482300566e-07 1

                    somatic  VEP_germline
0
stop_gained            27.8           8.0
frameshift_variant    574.8          20.0

[[ 34.21040279   1.58959721]
 [568.38959721  26.41040279]]

                     somatic  VEP_germline
0
stop_gained        -5.355447      5.355447
frameshift_variant  5.355447     -5.355447

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/CEBPA
1209
1141
1141
972
2113
54930

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained           845.0          41.0
frameshift_variant    636.8          77.0

somatic         1481.8
VEP_germline     118.0
dtype: float64
21.062811381453567 4.444710811250608e-06 1

                    somatic  VEP_germline
0
stop_gained           845.0          41.0
frameshift_variant    636.8          77.0

[[820.64933117  65.35066883]
 [661.15066883  52.64933117]]

                     somatic  VEP_germline
0
stop_gained         4.685636     -4.685636
frameshift_variant -4.685636      4.685636

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/CDKN2A
204
187
181
78
259
55189

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained            85.0          32.0
frameshift_variant    146.2          61.0

somatic         231.2
VEP_germline     93.0
dtype: float64
0.07381507610851049 0.785860928765793 1

                    somatic  VEP_germline
0
stop_gained            85.0          32.0
frameshift_variant    146.2          61.0

[[ 83.43738433  33.56261567]
 [147.76261567  59.43738433]]

                     somatic  VEP_germline
0
stop_gained         0.399529     -0.399529
frameshift_variant -0.399529      0.399529

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/CDKN1B
713
704
704

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

180
884
56073

                    somatic  VEP_germline
0
stop_gained           214.4         219.0
frameshift_variant    411.8         436.0

somatic         626.2
VEP_germline    655.0
dtype: float64
0.059861991994956676 0.8067142008439693 1

                    somatic  VEP_germline
0
stop_gained           214.4         219.0
frameshift_variant    411.8         436.0

[[211.82881673 221.57118327]
 [414.37118327 433.42881673]]

                     somatic  VEP_germline
0
stop_gained         0.303732     -0.303732
frameshift_variant -0.303732      0.303732

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/CDH1
51
49
49
81
130
56203

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained            41.4          55.0
frameshift_variant     50.6          58.0

somatic          92.0
VEP_germline    113.0
dtype: float64
0.1469341017929291 0.7014826284760439 1

                    somatic  VEP_germline
0
stop_gained            41.4          55.0
frameshift_variant     50.6          58.0

[[43.26243902 53.13756098]
 [48.73756098 59.86243902]]

                     somatic  VEP_germline
0
stop_gained        -0.523994      0.523994
frameshift_variant  0.523994     -0.523994

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/CDC73
370
320
309
198
505
56708

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained           154.8        3995.0
frameshift_variant    273.2       11095.0

somatic           428.0
VEP_germline    15090.0
dtype: float64
19.471554391143467 1.021090248424632e-05 1

                    somatic  VEP_germline
0
stop_gained           154.8        3995.0
frameshift_variant    273.2       11095.0

[[  114.45511019  4035.34488981]
 [  313.54488981 11054.65511019]]

                     somatic  VEP_germline
0
stop_gained         4.468031     -4.468031
frameshift_variant -4.468031      4.468031

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/BRCA2
178
165
164
115
277
56985

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained            90.4        3031.0
frameshift_variant    121.4        7822.0

somatic           211.8
VEP_germline    10853.0
dtype: float64
21.60716966354763 3.3459872827259386e-06 1

                    somatic  VEP_germline
0
stop_gained            90.4        3031.0
frameshift_variant    121.4        7822.0

[[  59.7491613 3061.6508387]
 [ 152.0508387 7791.3491613]]

                     somatic  VEP_germline
0
stop_gained         4.725436     -4.725436
frameshift_variant -4.725436      4.725436

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/BRCA1
45
42
42
17
59
57044

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained            19.8          96.0
frameshift_variant     20.0         134.0

somatic          39.8
VEP_germline    230.0
dtype: float64
0.5916157982648051 0.4417949788785346 1

                    somatic  VEP_germline
0
stop_gained            19.8          96.0
frameshift_variant     20.0         134.0

[[ 17.08243143  98.71756857]
 [ 22.71756857 131.28243143]]

                     somatic  VEP_germline
0
stop_gained         0.942591     -0.942591
frameshift_variant -0.942591      0.942591

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/BMPR1A

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

59
51
50
15
64
57108

                    somatic  VEP_germline
0
stop_gained            26.0         276.0
frameshift_variant     29.0         383.0

somatic          55.0
VEP_germline    659.0
dtype: float64
0.4037902061167994 0.5251382997667604 1

                    somatic  VEP_germline
0
stop_gained            26.0         276.0
frameshift_variant     29.0         383.0

[[ 23.26330532 278.73669468]
 [ 31.73669468 380.26330532]]

                     somatic  VEP_germline
0
stop_gained         0.777495     -0.777495
frameshift_variant -0.777495      0.777495

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/BARD1
574
456
453
400
852

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

57960

                    somatic  VEP_germline
0
stop_gained           224.2          88.0
frameshift_variant    410.6         207.0

somatic         634.8
VEP_germline    295.0
dtype: float64
2.479013794752837 0.11537457585515576 1

                    somatic  VEP_germline
0
stop_gained           224.2          88.0
frameshift_variant    410.6         207.0

[[213.14751559  99.05248441]
 [421.65248441 195.94751559]]

                     somatic  VEP_germline
0
stop_gained         1.649091     -1.649091
frameshift_variant -1.649091      1.649091

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/BAP1
151
132
131
104
235
58195

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained            26.6          49.0
frameshift_variant    185.8          90.0

somatic         212.4
VEP_germline    139.0
dtype: float64
24.374802853362283 7.929913881046962e-07 1

                    somatic  VEP_germline
0
stop_gained            26.6          49.0
frameshift_variant    185.8          90.0

[[ 45.69561753  29.90438247]
 [166.70438247 109.09561753]]

                     somatic  VEP_germline
0
stop_gained        -5.069833      5.069833
frameshift_variant  5.069833     -5.069833

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/AXIN2
808
717
712
443
1153
59348

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

                    somatic  VEP_germline
0
stop_gained           401.8        1453.0
frameshift_variant    356.0        2685.0

somatic          757.8
VEP_germline    4138.0
dtype: float64
86.53078092054236 1.3757921050461605e-20 1

                    somatic  VEP_germline
0
stop_gained           401.8        1453.0
frameshift_variant    356.0        2685.0

[[ 287.09658074 1567.70341926]
 [ 470.70341926 2570.29658074]]

                     somatic  VEP_germline
0
stop_gained         9.342919     -9.342919
frameshift_variant -9.342919      9.342919

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/ATM
4060
3978
3963
4977
8940

/var/folders/84/djb4q50s33b6t8_cvx6h9src0000gn/T/ipykernel_73898/1991680147.py:94: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  somaticconcat["patientid"]=somaticconcat["patientId"].astype("str")+somaticconcat["INDIVIDUAL_ID"].astype("str")

68288

                    somatic  VEP_germline
0
stop_gained          3776.2         866.0
frameshift_variant   2814.4        1507.0

somatic         6590.6
VEP_germline    2373.0
dtype: float64
301.582305921137 1.489509151622139e-67 1

                    somatic  VEP_germline
0
stop_gained          3776.2         866.0
frameshift_variant   2814.4        1507.0

[[3413.23612388 1228.96387612]
 [3177.36387612 1144.03612388]]

                      somatic  VEP_germline
0
stop_gained         17.390081    -17.390081
frameshift_variant -17.390081     17.390081

FLAG5 = 0
Current directory: /Users/suhasinilulla/Library/CloudStorage/Box-Box/PhD_BCM/Lulla_Plon_Lab/High_priority_gene_list/GL_S_Pipeline_1st_pass_47TSGs_May2023/APC
Thu Jun 19 14:33:03 2025